import { useHubLang, type HubLang } from "@/lib/hub-lang";

/** Kid chrome. rw, ti, and fa-AF need a native check. See the shop note. */
const COPY = {
  en: {
    pick: "Pick a lab. Fold the paper to match the picture.",
    start: "Start",
    labs: "Labs",
    skills: "Skills",
    studio: "Studio",
    teacher: "Teacher desk",
    words: "Words",
    nextStep: "Next step",
    weMade: "We made this",
    made: "Made on this Chromebook",
    before: "Before it counts",
    didLast: "I did the last step.",
    passed: "The test passed.",
    linesTitle: "How to read the lines",
    cutLine: "A thick line is a cut.",
    foldLine: "A dashed line is a fold toward you.",
    stopLine: "Do not cut a dashed line.",
    finish: "Finish the steps and pass the test. Then it counts.",
    shopRule: "Shop rule.",
    scissors: "Scissors stay on the desk. Pass them closed, handle first.",
    step: "Step",
  },
  simple: {
    pick: "Pick a lab. Fold it like the picture.",
    start: "Start",
    labs: "Labs",
    skills: "Skills",
    studio: "Studio",
    teacher: "Teacher desk",
    words: "Words",
    nextStep: "Next",
    weMade: "We made this",
    made: "Made on this Chromebook",
    before: "Before it counts",
    didLast: "I did the last step.",
    passed: "The test passed.",
    linesTitle: "How to read the lines",
    cutLine: "Thick line. Cut.",
    foldLine: "Dashed line. Fold toward you.",
    stopLine: "Do not cut a dashed line.",
    finish: "Do the steps. Pass the test. Then it counts.",
    shopRule: "Shop rule.",
    scissors: "Scissors stay on the desk. Pass them closed, handles first.",
    step: "Step",
  },
  uk: {
    pick: "Обери роботу. Склади папір, як на малюнку.",
    start: "Почати",
    labs: "Роботи",
    skills: "Вміння",
    studio: "Майстерня",
    teacher: "Стіл учителя",
    words: "Слова",
    nextStep: "Далі",
    weMade: "Ми це зробили",
    made: "Зроблено на цьому Chromebook",
    before: "Перш ніж зарахувати",
    didLast: "Я зробив останній крок.",
    passed: "Перевірка вдалася.",
    linesTitle: "Як читати лінії",
    cutLine: "Товста лінія — це розріз.",
    foldLine: "Пунктир — згин до себе.",
    stopLine: "Пунктир не ріж.",
    finish: "Зроби всі кроки і пройди перевірку. Тоді зарахує.",
    shopRule: "Правило майстерні.",
    scissors: "Ножиці лишаються на столі. Передавай їх закритими, ручками вперед.",
    step: "Крок",
  },
  ru: {
    pick: "Выбери работу. Сложи бумагу, как на рисунке.",
    start: "Начать",
    labs: "Работы",
    skills: "Умения",
    studio: "Мастерская",
    teacher: "Стол учителя",
    words: "Слова",
    nextStep: "Дальше",
    weMade: "Мы это сделали",
    made: "Сделано на этом Chromebook",
    before: "Прежде чем засчитать",
    didLast: "Я сделал последний шаг.",
    passed: "Проверка пройдена.",
    linesTitle: "Как читать линии",
    cutLine: "Толстая линия — это разрез.",
    foldLine: "Пунктир — сгиб к себе.",
    stopLine: "Пунктир не режь.",
    finish: "Сделай все шаги и пройди проверку. Тогда засчитают.",
    shopRule: "Правило мастерской.",
    scissors: "Ножницы остаются на столе. Передавай их закрытыми, ручками вперёд.",
    step: "Шаг",
  },
  es: {
    pick: "Elige un laboratorio. Dobla el papel para que coincida con el dibujo.",
    start: "Empezar",
    labs: "Laboratorios",
    skills: "Destrezas",
    studio: "Taller",
    teacher: "Mesa del maestro",
    words: "Palabras",
    nextStep: "Siguiente paso",
    weMade: "Lo hicimos",
    made: "Hecho en esta Chromebook",
    before: "Antes de que cuente",
    didLast: "Hice el último paso.",
    passed: "La prueba salió bien.",
    linesTitle: "Cómo leer las líneas",
    cutLine: "Una línea gruesa se corta.",
    foldLine: "Una línea de rayas se dobla hacia ti.",
    stopLine: "No cortes una línea de rayas.",
    finish: "Termina los pasos y pasa la prueba. Entonces cuenta.",
    shopRule: "Regla del taller.",
    scissors: "Las tijeras se quedan en la mesa. Pásalas cerradas, el mango primero.",
    step: "Paso",
  },
  ar: {
    pick: "اختر عملاً. اطوِ الورقة لتطابق الصورة.",
    start: "ابدأ",
    labs: "الأعمال",
    skills: "المهارات",
    studio: "الورشة",
    teacher: "طاولة المعلّم",
    words: "كلمات",
    nextStep: "الخطوة التالية",
    weMade: "صنعنا هذا",
    made: "تم على هذا الجهاز",
    before: "قبل أن يُحتسب",
    didLast: "عملت الخطوة الأخيرة.",
    passed: "نجح الاختبار.",
    linesTitle: "كيف تقرأ الخطوط",
    cutLine: "الخط السميك للقص.",
    foldLine: "الخط المتقطع للطي نحوك.",
    stopLine: "لا تقص الخط المتقطع.",
    finish: "أنهِ الخطوات وانجح في الاختبار. عندها يُحتسب.",
    shopRule: "قاعدة الورشة.",
    scissors: "المقص يبقى على الطاولة. مرّره مغلقاً، المقبض أولاً.",
    step: "خطوة",
  },
  "fa-AF": {
    pick: "یک کار را انتخاب کن. کاغذ را مثل تصویر تا کن.",
    start: "شروع",
    labs: "لابراتوارها",
    skills: "مهارت‌ها",
    studio: "کارگاه",
    teacher: "میز معلم",
    words: "واژه‌ها",
    nextStep: "قدم بعدی",
    weMade: "این را ساختیم",
    made: "در همین کمپیوتر ساخته شد",
    before: "پیش از آنکه حساب شود",
    didLast: "قدم آخر را کردم.",
    passed: "آزمون درست شد.",
    linesTitle: "خط‌ها را چطور بخوانی",
    cutLine: "خط ضخیم برای بریدن است.",
    foldLine: "خط قطعه‌قطعه برای تا کردن به طرف خودت است.",
    stopLine: "خط قطعه‌قطعه را نبر.",
    finish: "قدم‌ها را تمام کن و آزمون را بگذران. بعد حساب می‌شود.",
    shopRule: "قانون کارگاه.",
    scissors: "قیچی روی میز می‌ماند. آن را بسته بده، دسته اول.",
    step: "قدم",
  },
  rw: {
    pick: "Hitamo umurimo. Zinga impapuro nk'ishusho.",
    start: "Tangira",
    labs: "Amasomo",
    skills: "Ubuhanga",
    studio: "Sitidiyo",
    teacher: "Ibiro by'umwarimu",
    words: "Amagambo",
    nextStep: "Intambwe ikurikira",
    weMade: "Twabikoze",
    made: "Byakozwe kuri iyi mudasobwa",
    before: "Mbere yo kubarwa",
    didLast: "Nakoze intambwe ya nyuma.",
    passed: "Ikizamini cyagenze neza.",
    linesTitle: "Uko usoma imirongo",
    cutLine: "Umurongo muto ni ugucagagura.",
    foldLine: "Umurongo w'uduce ni ugukata ukwerekeza.",
    stopLine: "Ntucagagure umurongo w'uduce.",
    finish: "Rangiza intambwe kandi utsinde ikizamini. Hanyuma birabarwa.",
    shopRule: "Itegeko ry'ikoro.",
    scissors: "Imakasi ziguma ku meza. Zitangire zifunze, umukono mbere.",
    step: "Intambwe",
  },
  ti: {
    pick: "ሓደ ስራሕ ምረጽ። ወረቐት ከም ስእሊ ዓጽፎ።",
    start: "ጀምር",
    labs: "ላባት",
    skills: "ክእለታት",
    studio: "ስቱዲዮ",
    teacher: "ጣውላ መምህር",
    words: "ቃላት",
    nextStep: "ዝቕጽል ስጉምቲ",
    weMade: "እዚ ገይርናዮ",
    made: "ኣብዚ ኮምፒተር ተገይሩ",
    before: "ቅድሚ ምቑጻር",
    didLast: "ናይ መወዳእታ ስጉምቲ ገይረ።",
    passed: "ፈተና ተሓሊፉ።",
    linesTitle: "መስመራት ከመይ ትንብቦም",
    cutLine: "ሸነኽ መስመር ንምቑራጽ እዩ።",
    foldLine: "ዝተቆረጸ መስመር ናባኻ ንምዕጻፍ እዩ።",
    stopLine: "ዝተቆረጸ መስመር ኣይትቑረጽ።",
    finish: "ስጉምትታት ወድእ እሞ ፈተና ሕለፍ። እዚኣ እዩ ዝቑጸር።",
    shopRule: "ሕጊ መደበር።",
    scissors: "መቐዝ ኣብ ሰደቓ ይጽናሕ። ዕጹው ሃቦ፣ ኢድ መጀመርታ።",
    step: "ስጉምቲ",
  },
} as const;

export type CopyKey = keyof (typeof COPY)["en"];

const LINES: Record<string, Record<string, string>> = {
  uk: {
    "Put one scrap flat on the desk": "Поклади один клаптик рівно на стіл",
    "Point to the left edge": "Покажи на лівий край",
    "Point to the right edge": "Покажи на правий край",
    "Fold the paper toward you, the way the picture shows": "Склади папір до себе, як на малюнку",
    "Stop when the paper makes a V": "Зупинись, коли папір стане літерою V",
    "Press the crease with a fingernail": "Притисни згин нігтем",
    "Leave it folded": "Залиш складеним",
    "Say valley": "Скажи: долина",
    "Open the scrap": "Розгорни клаптик",
    "Turn the paper over": "Переверни папір",
    "Fold it away from you, the way the picture shows": "Склади від себе, як на малюнку",
    "Press the crease": "Притисни згин",
    "Say mountain": "Скажи: гора",
    "Same crease. Valley on one side. Mountain on the other": "Той самий згин. Долина з одного боку. Гора з іншого",
    "Take a new scrap": "Візьми новий клаптик",
    "Fold one edge to the opposite edge": "Склади один край до протилежного",
    "Press with a fingernail": "Притисни нігтем",
    "Open it. The line stays. That is fold-and-unfold": "Розгорни. Лінія лишається. Це склав-і-розгорнув",
    "Point to the dashed line in the picture": "Покажи на пунктир на малюнку",
    "Say: dashed means valley": "Скажи: пунктир означає долину",
    "Open Fold quiz. Pass is 3 out of 4": "Відкрий вікторину згинів. Залік — 3 з 4",
    "Scrap flat": "Клаптик рівно",
    "Valley toward you": "Долина до себе",
    "Mountain away": "Гора від себе",
    "Fold and unfold": "Склади і розгорни",
    "Dashed means valley": "Пунктир означає долину",
  },
  ru: {
    "Put one scrap flat on the desk": "Положи один клочок ровно на стол",
    "Point to the left edge": "Покажи на левый край",
    "Point to the right edge": "Покажи на правый край",
    "Fold the paper toward you, the way the picture shows": "Сложи бумагу к себе, как на рисунке",
    "Stop when the paper makes a V": "Остановись, когда бумага станет буквой V",
    "Press the crease with a fingernail": "Прижми сгиб ногтем",
    "Leave it folded": "Оставь сложенной",
    "Say valley": "Скажи: долина",
    "Open the scrap": "Разверни клочок",
    "Turn the paper over": "Переверни бумагу",
    "Fold it away from you, the way the picture shows": "Сложи от себя, как на рисунке",
    "Press the crease": "Прижми сгиб",
    "Say mountain": "Скажи: гора",
    "Same crease. Valley on one side. Mountain on the other": "Тот же сгиб. Долина с одной стороны. Гора с другой",
    "Take a new scrap": "Возьми новый клочок",
    "Fold one edge to the opposite edge": "Сложи один край к противоположному",
    "Press with a fingernail": "Прижми ногтем",
    "Open it. The line stays. That is fold-and-unfold": "Разверни. Линия остаётся. Это сложил-и-развернул",
    "Point to the dashed line in the picture": "Покажи на пунктир на рисунке",
    "Say: dashed means valley": "Скажи: пунктир значит долина",
    "Open Fold quiz. Pass is 3 out of 4": "Открой викторину сгибов. Зачёт — 3 из 4",
    "Scrap flat": "Клочок ровно",
    "Valley toward you": "Долина к себе",
    "Mountain away": "Гора от себя",
    "Fold and unfold": "Сложи и разверни",
    "Dashed means valley": "Пунктир значит долина",
  },
  es: {
    "Put one scrap flat on the desk": "Pon un recorte plano en la mesa",
    "Point to the left edge": "Señala el borde izquierdo",
    "Point to the right edge": "Señala el borde derecho",
    "Fold the paper toward you, the way the picture shows": "Dobla el papel hacia ti, como en el dibujo",
    "Stop when the paper makes a V": "Para cuando el papel haga una V",
    "Press the crease with a fingernail": "Aprieta el doblez con una uña",
    "Leave it folded": "Déjalo doblado",
    "Say valley": "Di: valle",
    "Open the scrap": "Abre el recorte",
    "Turn the paper over": "Voltea el papel",
    "Fold it away from you, the way the picture shows": "Dóblalo lejos de ti, como en el dibujo",
    "Press the crease": "Aprieta el doblez",
    "Say mountain": "Di: montaña",
    "Same crease. Valley on one side. Mountain on the other": "El mismo doblez. Valle de un lado. Montaña del otro",
    "Take a new scrap": "Toma un recorte nuevo",
    "Fold one edge to the opposite edge": "Dobla un borde hasta el borde de enfrente",
    "Press with a fingernail": "Aprieta con una uña",
    "Open it. The line stays. That is fold-and-unfold": "Ábrelo. La línea se queda. Eso es doblar y desdoblar",
    "Point to the dashed line in the picture": "Señala la línea de rayas en el dibujo",
    "Say: dashed means valley": "Di: las rayas significan valle",
    "Open Fold quiz. Pass is 3 out of 4": "Abre el quiz de dobleces. Pasar es 3 de 4",
    "Scrap flat": "Recorte plano",
    "Valley toward you": "Valle hacia ti",
    "Mountain away": "Montaña lejos",
    "Fold and unfold": "Doblar y desdoblar",
    "Dashed means valley": "Las rayas significan valle",
  },
  ar: {
    "Put one scrap flat on the desk": "ضع قصاصة واحدة مسطحة على الطاولة",
    "Point to the left edge": "أشر إلى الحافة اليسرى",
    "Point to the right edge": "أشر إلى الحافة اليمنى",
    "Fold the paper toward you, the way the picture shows": "اطوِ الورقة نحوك كما في الصورة",
    "Stop when the paper makes a V": "توقف عندما تصير الورقة حرف V",
    "Press the crease with a fingernail": "اضغط الثنية بالظفر",
    "Leave it folded": "اتركها مطوية",
    "Say valley": "قل: وادي",
    "Open the scrap": "افتح القصاصة",
    "Turn the paper over": "اقلب الورقة",
    "Fold it away from you, the way the picture shows": "اطوها بعيداً عنك كما في الصورة",
    "Press the crease": "اضغط الثنية",
    "Say mountain": "قل: جبل",
    "Same crease. Valley on one side. Mountain on the other": "نفس الثنية. وادي من جهة. جبل من الجهة الأخرى",
    "Take a new scrap": "خذ قصاصة جديدة",
    "Fold one edge to the opposite edge": "اطوِ حافة إلى الحافة المقابلة",
    "Press with a fingernail": "اضغط بالظفر",
    "Open it. The line stays. That is fold-and-unfold": "افتحها. الخط يبقى. هذا طي ثم فتح",
    "Point to the dashed line in the picture": "أشر إلى الخط المتقطع في الصورة",
    "Say: dashed means valley": "قل: المتقطع يعني وادي",
    "Open Fold quiz. Pass is 3 out of 4": "افتح اختبار الطي. النجاح 3 من 4",
    "Scrap flat": "قصاصة مسطحة",
    "Valley toward you": "وادي نحوك",
    "Mountain away": "جبل بعيداً",
    "Fold and unfold": "طي ثم فتح",
    "Dashed means valley": "المتقطع يعني وادي",
  },
  "fa-AF": {
    "Put one scrap flat on the desk": "یک تکه کاغذ را هموار روی میز بگذار",
    "Point to the left edge": "لبه چپ را نشان بده",
    "Point to the right edge": "لبه راست را نشان بده",
    "Fold the paper toward you, the way the picture shows": "کاغذ را به طرف خودت تا کن، مثل تصویر",
    "Stop when the paper makes a V": "وقتی کاغذ شکل V شد، بایست",
    "Press the crease with a fingernail": "خط تا را با ناخن فشار بده",
    "Leave it folded": "تا شده بگذار",
    "Say valley": "بگو: دره",
    "Open the scrap": "تکه را باز کن",
    "Turn the paper over": "کاغذ را برگردان",
    "Fold it away from you, the way the picture shows": "آن را از خودت دور تا کن، مثل تصویر",
    "Press the crease": "خط تا را فشار بده",
    "Say mountain": "بگو: کوه",
    "Same crease. Valley on one side. Mountain on the other": "همان خط تا. یک طرف دره. طرف دیگر کوه",
    "Take a new scrap": "یک تکه نو بگیر",
    "Fold one edge to the opposite edge": "یک لبه را به لبه روبرو تا کن",
    "Press with a fingernail": "با ناخن فشار بده",
    "Open it. The line stays. That is fold-and-unfold": "باز کن. خط می‌ماند. این تا کردن و باز کردن است",
    "Point to the dashed line in the picture": "خط قطعه‌قطعه را در تصویر نشان بده",
    "Say: dashed means valley": "بگو: خط قطعه‌قطعه یعنی دره",
    "Open Fold quiz. Pass is 3 out of 4": "آزمون تا را باز کن. کامیابی ۳ از ۴ است",
    "Scrap flat": "تکه هموار",
    "Valley toward you": "دره به طرف خودت",
    "Mountain away": "کوه دور از خودت",
    "Fold and unfold": "تا کن و باز کن",
    "Dashed means valley": "قطعه‌قطعه یعنی دره",
  },
  rw: {
    "Put one scrap flat on the desk": "Shyira agace kamwe karambuye ku meza",
    "Point to the left edge": "Erekana uruhande rw'ibumoso",
    "Point to the right edge": "Erekana uruhande rw'iburyo",
    "Fold the paper toward you, the way the picture shows": "Zinga impapuro ukwerekeza, nk'ishusho",
    "Stop when the paper makes a V": "Hagarara impapuro imaze gukora V",
    "Press the crease with a fingernail": "Kanda umurongo w'umuzingo n'urwara",
    "Leave it folded": "Uyireke izanzwe",
    "Say valley": "Vuga: akabande",
    "Open the scrap": "Fungura agace",
    "Turn the paper over": "Hindura impapuro",
    "Fold it away from you, the way the picture shows": "Izinge ukayirenza, nk'ishusho",
    "Press the crease": "Kanda umurongo",
    "Say mountain": "Vuga: umusozi",
    "Same crease. Valley on one side. Mountain on the other": "Umurongo umwe. Akabande ku ruhande rumwe. Umusozi ku rundi",
    "Take a new scrap": "Fata agace gashya",
    "Fold one edge to the opposite edge": "Zinga uruhande rugere ku rundi",
    "Press with a fingernail": "Kanda n'urwara",
    "Open it. The line stays. That is fold-and-unfold": "Yifungure. Umurongo usigara. Ni uguzinga no gufungura",
    "Point to the dashed line in the picture": "Erekana umurongo w'uduce ku ishusho",
    "Say: dashed means valley": "Vuga: uduce bisobanura akabande",
    "Open Fold quiz. Pass is 3 out of 4": "Fungura ikizamini cy'imizingo. Gutsinda ni 3 muri 4",
    "Scrap flat": "Agace karambuye",
    "Valley toward you": "Akabande kukwerekeza",
    "Mountain away": "Umusozi ukurenga",
    "Fold and unfold": "Zinga hanyuma ufungure",
    "Dashed means valley": "Uduce bisobanura akabande",
  },
  ti: {
    "Put one scrap flat on the desk": "ሓደ ቁራጽ ወረቐት ብጽርየት ኣብ ሰደቓ ኣቐምጥ",
    "Point to the left edge": "ጸጋማይ ወሰን ኣርኢ",
    "Point to the right edge": "የማናይ ወሰን ኣርኢ",
    "Fold the paper toward you, the way the picture shows": "ወረቐት ናባኻ ዓጽፎ፣ ከም ስእሊ",
    "Stop when the paper makes a V": "ወረቐት V ምስ ኮነ ደው ኢልካ",
    "Press the crease with a fingernail": "መስመር ዕጸፋ ብጽፍሪ ጸቕጦ",
    "Leave it folded": "ተዓጺፉ ግደፎ",
    "Say valley": "በል፡ ሸለቆ",
    "Open the scrap": "ቁራጽ ክፈት",
    "Turn the paper over": "ወረቐት ገልብጥ",
    "Fold it away from you, the way the picture shows": "ካባኻ ርሒቑ ዓጽፎ፣ ከም ስእሊ",
    "Press the crease": "መስመር ዕጸፋ ጸቕጦ",
    "Say mountain": "በል፡ ከበሳ",
    "Same crease. Valley on one side. Mountain on the other": "ሓደ መስመር። ሓደ ጎኒ ሸለቆ። ካልእ ጎኒ ከበሳ",
    "Take a new scrap": "ሓድሽ ቁራጽ ውሰድ",
    "Fold one edge to the opposite edge": "ሓደ ወሰን ናብ ቅድሚኡ ዓጽፎ",
    "Press with a fingernail": "ብጽፍሪ ጸቕጦ",
    "Open it. The line stays. That is fold-and-unfold": "ክፈቶ። መስመር ይተርፍ። እዚ ምዕጻፍን ምኽፋትን እዩ",
    "Point to the dashed line in the picture": "ዝተቆረጸ መስመር ኣብ ስእሊ ኣርኢ",
    "Say: dashed means valley": "በል፡ ዝተቆረጸ መስመር ሸለቆ ማለት እዩ",
    "Open Fold quiz. Pass is 3 out of 4": "ፈተና ዕጸፋ ክፈት። ምሕላፍ 3 ካብ 4 እዩ",
    "Scrap flat": "ጽሩይ ቁራጽ",
    "Valley toward you": "ሸለቆ ናባኻ",
    "Mountain away": "ከበሳ ካባኻ",
    "Fold and unfold": "ዓጽፍ እሞ ክፈት",
    "Dashed means valley": "ዝተቆረጸ መስመር ሸለቆ እዩ",
  },
};

export function textOf(lang: HubLang, key: CopyKey) {
  const table = COPY[lang] ?? COPY.en;
  return table[key] || COPY.en[key];
}

export function lineOf(lang: HubLang, english: string) {
  if (lang === "en" || lang === "simple") return english;
  return LINES[lang]?.[english] || english;
}

export function useCopy() {
  const lang = useHubLang();
  return (key: CopyKey) => textOf(lang, key);
}

export function useLine() {
  const lang = useHubLang();
  return (english: string) => lineOf(lang, english);
}
