import type { Lab } from "./labs";

const c = (easy: string, classText: string, stretch: string) => ({
  easy,
  class: classText,
  stretch,
});

/** Take-home crafts with a testable spec. Same sheet, same period, something you keep. */
export const CRAFT_LABS: Lab[] = [
  {
    id: "kite",
    name: "Diamond kite",
    family: "fly",
    teConcept: "A sail, a bridle, and a tail: lift plus a damper so the kite does not spin",
    grades: "3–8",
    time: "35–45 min",
    materials: ["1 sheet", "leftover strip for the tail", "about 1 m of string or yarn", "2 small tape bits for the bridle"],
    mst: ["ED", "TS", "TR", "HT"],
    blurb: c(
      "Fold a diamond. Tie a tail from the leftover strip. Walk it. It should lift and not spin.",
      "A kite is a flying system: sail, bridle, tail. The tail damps spin. Two of three trials must lift for a count of five.",
      "The bridle sets angle of attack. A tail is a yaw damper, not decoration. History: paper kites as tools, then toys.",
    ),
    challenge: "Lift and stay up for a slow count of 5, 2 of 3 trials. Tail from the leftover strip. Do not run.",
    spec: "Pass: lifts off the hand or hangs in a doorway breeze for 5 s without spinning. Stretch: a walking tow past a 4 m tape.",
    steps: [
      {
        title: "Square",
        minutes: "4 min",
        visual: "square-cut",
        body: c(
          "Fold a short edge onto a long edge. Cut off the extra strip. Open the square. Keep the strip for the tail.",
          "The square, turned on a point, is the diamond. The strip is the tail.",
          "A rectangle sail is a different kite. Square first.",
        ),
      },
      {
        title: "Spine",
        minutes: "3 min",
        visual: "kite-spine",
        body: c(
          "Turn the square so a point is up. Fold the top point down to the bottom point. Press. Open it. That line is the spine.",
          "One diagonal. The sail stays a diamond.",
          "Do not cut the diamond apart.",
        ),
      },
      {
        title: "Bridle",
        minutes: "4 min",
        visual: "kite-bridle",
        body: c(
          "Tape one end of the string near the top point. Tape the other end on the spine, a little past the middle. The loop you hold is the bridle.",
          "Two small pieces of tape. Not a wrap.",
          "The lower tape sets the angle. Too low and it dives.",
        ),
      },
      {
        title: "Tail",
        minutes: "3 min",
        visual: "kite-tail",
        body: c(
          "Tape the leftover strip to the bottom point. That is the tail.",
          "A short tail spins. A very long tail will not lift.",
          "Start with the whole strip. You can shorten it later.",
        ),
      },
      {
        title: "Walk",
        minutes: "5 min",
        visual: "kite-fly",
        body: c(
          "Walk. Do not run. Hold the string. Count to five. Did it lift? Did it spin?",
          "Hallway or gym. Three walks.",
          "Spin means more tail. No lift means move the lower tape or find more air.",
        ),
      },
      {
        title: "One change",
        minutes: "5 min",
        visual: "iterate",
        body: c(
          "Make the tail longer, or move the lower tape. Walk three more times.",
          "One change only.",
          "Write which one you changed.",
        ),
      },
    ],
    vocab: [
      { term: "sail", meaning: "The paper that catches the air", es: "vela" },
      { term: "bridle", meaning: "The two-point string that sets the tilt", es: "brida" },
      { term: "tail", meaning: "A streamer that stops the spin", es: "cola" },
    ],
    ell: "Diamond. String in two places. Long tail. Walk. Count five. No running.",
    sped: "Pre-cut diamond. Student tapes bridle and tail, then walks the test. Doorway hang if walking is hard.",
    ta: "Walk. If they start to run: stop, reset at the line. You may hold the sail while they tape.",
    plan: {
      hook: "A sheet wants to tumble. A tail and a bridle turn tumble into lift.",
      objectives: ["Build a diamond kite with a bridle and a leftover tail.", "Run a counted lift test.", "Change one geometry and report the fail mode."],
      assessment: ["2 of 3 lifts of 5 s.", "Tail from leftover, not a new sheet.", "Fail mode named."],
      snags: ["Running.", "Tape wrapping the whole sail.", "No tail, then blaming the wind."],
      extend: "A two-cell box kite from a second sheet. Compare stability.",
    },
  },
  {
    id: "bag",
    name: "Carry bag",
    family: "make",
    teConcept: "A grocery bag is packaging: folded bottom, gussets, handles in tension",
    grades: "3–8",
    time: "35–45 min",
    materials: ["1–2 sheets", "scissors", "glue stick or 4 tape strips"],
    mst: ["ED", "TR", "TS", "HT"],
    blurb: c(
      "Fold a bag with a flat bottom and two handles. Carry a load across the room. If a handle tears, that is data.",
      "A paper grocery bag is a manufactured container. Folded square bottom, side gussets, handles as tension members. Carry six glue sticks 3 m.",
      "Handles fail in tension; bottoms fail in shear. You choose whether to spend tape on the handle joint or the floor joint — a resource tradeoff.",
    ),
    challenge: "Carry six glue sticks (or one small book) across a 3 m tape without tearing. Handles required.",
    spec: "Pass: load stays in, handles hold, 3 m walk, hands only on the handles. Stretch: one sheet only, or a folded bottom with no tape.",
    steps: [
      {
        title: "Middle",
        minutes: "3 min",
        visual: "bag-middle",
        body: c(
          "Hold the sheet tall. Fold the left edge to the right edge. Press. Open it. The middle line stays.",
          "That line is the middle of the bag.",
          "A skewed fold makes a bag that will not sit.",
        ),
      },
      {
        title: "Tube",
        minutes: "4 min",
        visual: "bag-tube",
        body: c(
          "Glue or tape the two long edges together. You have a tube.",
          "Overlap about a finger. Press.",
          "The seam is a joint. Name it.",
        ),
      },
      {
        title: "Triangles",
        minutes: "4 min",
        visual: "bag-triangles",
        body: c(
          "Fold the bottom up a little. Push the left side in. Push the right side in. Two triangles show.",
          "Those triangles are the gussets.",
          "If they are uneven, the bottom will be crooked.",
        ),
      },
      {
        title: "Flaps",
        minutes: "4 min",
        visual: "bag-flaps",
        body: c(
          "Fold one bottom flap over the triangles. Fold the other flap over. Glue them.",
          "The bottom should sit flat.",
          "A bag that rocks has a skewed seam.",
        ),
      },
      {
        title: "Handles",
        minutes: "5 min",
        visual: "bag-handles",
        body: c(
          "Glue one strip into a loop inside the rim. Glue a second loop on the other side. Press.",
          "Handles go on the inside, not on the thin edge.",
          "A handle on the edge peels off.",
        ),
      },
      {
        title: "Carry",
        minutes: "4 min",
        visual: "bag-load",
        body: c(
          "Put six glue sticks in the bag. Hold the handles. Walk. If it tears, look at the handle or the bottom.",
          "Hands on the handles only.",
          "Write which part tore.",
        ),
      },
      {
        title: "One joint",
        minutes: "4 min",
        visual: "iterate",
        body: c(
          "Fix the part that tore. Use the same load. Walk again.",
          "One change.",
          "A second sheet is stronger and uses more paper. Name that.",
        ),
      },
    ],
    vocab: [
      { term: "gusset", meaning: "The folded side that lets a bag sit open", es: "fuelle" },
      { term: "handle", meaning: "The loop you carry; it pulls, it does not push", es: "asa" },
      { term: "hem", meaning: "A folded rim that makes a joint stronger", es: "dobladillo" },
    ],
    ell: "Tube. Fold the bottom. Glue handles inside. Six sticks. Walk. Where did it tear?",
    sped: "Teacher seams the tube. Student folds the floor and glues handles. Three glue sticks as the accessible load.",
    ta: "Do not carry it for them. If a handle peels mid-walk, catch the load — then they name the joint.",
    plan: {
      hook: "The store bag is a designed product. We will make one that has to work.",
      objectives: ["Fold a sitting bag with handles.", "Run a carry test.", "Repair the joint that failed."],
      assessment: ["3 m carry or a named fail joint.", "Handles used, not the rim.", "v2 aimed at the fail."],
      snags: ["Carrying under the floor like a tray.", "Tape sculpture instead of a bag.", "No hem on the handles."],
      extend: "Weigh the load. How many more sticks until fail? Graph it.",
    },
  },
  {
    id: "wallet",
    name: "Billfold",
    family: "make",
    teConcept: "A self-locking billfold: folded pockets, no fasteners, a shake test",
    grades: "3–8",
    time: "25–35 min",
    materials: ["1 sheet", "scissors", "three scrap cards"],
    mst: ["TR", "ED", "HT"],
    blurb: c(
      "Fold a wallet. Slide three scrap cards in. Shake ten times. If they fly, fold a tighter pocket.",
      "A billfold is packaging for paper. One sheet, folded pockets, no tape. Ten-shake test with three cards.",
      "Friction and a folded lip retain the load. Tape would be a different joining process — allowed only if you label it.",
    ),
    challenge: "Hold three scrap cards through a 10-shake test. No tape. It must open and close.",
    spec: "Pass: 3 cards, 10 shakes over a desk, cards stay, wallet still opens. Stretch: a bill pocket plus a card slot from one sheet.",
    steps: [
      {
        title: "Portrait valleys",
        minutes: "4 min",
        visual: "portrait-valleys",
        body: c(
          "Hold the sheet tall. Fold the left edge to the right edge. Press. Open it. Fold the bottom edge up to the middle. Press. Open it.",
          "Portrait · long valley · mid valley. Pocket zone is the lower half.",
          "A billfold starts as a folio. Pocket height is the design choice.",
        ),
      },
      {
        title: "Pocket · cover · hems",
        minutes: "8 min",
        visual: "pocket-cover-hems",
        body: c(
          "Fold the bottom third up. That is the pocket. Fold the top third down. That is the cover. Fold each side in a little. Those are the hems.",
          "Bottom third = pocket. Top third = cover. Side hems ~1 cm. Alias comes after the prove.",
          "Side hems retain the load. Skip them and the shake test will teach why.",
        ),
      },
      {
        title: "Load three cards",
        minutes: "4 min",
        visual: "load-cards",
        body: c(
          "Slide in one scrap card. Slide in a second card. Slide in a third card. Close the cover.",
          "Three cards. Too tight → taller pocket. Close cover · tuck OK.",
          "Fit is a spec: adjust pocket height, not card size.",
        ),
      },
      {
        title: "Ten-shake prove",
        minutes: "6 min",
        visual: "ten-shake",
        body: c(
          "Hold the wallet shut over the desk. Shake it ten times. All three cards must stay.",
          "10× shake over the desk. Prove first — no alias yet.",
          "Control: one shake with the flap open shows why the cover exists.",
        ),
      },
      {
        title: "One change · retest · alias",
        minutes: "6 min",
        visual: "one-change-retest",
        body: c(
          "Change one thing only. Make the pocket deeper, or make the sides tighter. Load three cards. Shake ten times again. Write your alias on the cover. No legal name.",
          "One change · retest · alias after prove. No hidden tape.",
          "Retention vs capacity. Name the tradeoff.",
        ),
      },
    ],
    vocab: [
      { term: "pocket", meaning: "The fold that holds the cards", es: "bolsillo" },
      { term: "billfold", meaning: "A wallet that folds around paper", es: "billetera" },
      { term: "hem", meaning: "A small side fold so cards cannot slide out", es: "dobladillo" },
    ],
    ell: "Fold up a pocket. Fold down a cover. Three cards. Shake ten. Count.",
    sped: "Pre-creased folio. Student only sets the pocket height and tests. Two cards as the accessible spec.",
    ta: "Shake over the desk, not the floor. Do not tuck the cards in “to help” before the count.",
    plan: {
      hook: "A wallet is a box for paper, folded so it lives in a pocket.",
      objectives: ["Fold a closing billfold.", "Run a 10-shake retention test.", "Add a hem or deeper pocket from fail data."],
      assessment: ["3 cards / 10 shakes or a named fail.", "Opens and closes after the test.", "No hidden tape unless labeled."],
      snags: ["Tape first.", "Shaking over the aisle.", "Cards too big so they cheat the pocket."],
      extend: "A coin pouch from the leftover. Does it change the shake?",
    },
  },
  {
    id: "frame",
    name: "Standing frame",
    family: "make",
    teConcept: "A display structure: a window, a lip, and a stand that has to wait",
    grades: "2–6",
    time: "25–35 min",
    materials: ["1 sheet", "scissors", "glue stick", "a drawing or 3×5 card"],
    mst: ["ED", "TR", "TS"],
    blurb: c(
      "Cut a window. Fold a stand. Put your drawing in. Hands off. Count to ten.",
      "A picture frame is a structure plus a display. Window, holding lip, easel stand. Hands off 10 s with a 3×5 card.",
      "The stand is a column in compression; the lip is a fixture. If it falls, name tip vs. buckle vs. slip.",
    ),
    challenge: "A standing frame that holds a 3×5 card (or a drawing) for 10 seconds, hands off.",
    spec: "Pass: stands 10 s, picture stays in the lip. Stretch: a folding easel back with no glue on the stand.",
    steps: [
      {
        title: "A card",
        minutes: "2 min",
        visual: "frame-card",
        body: c("Fold the sheet in half like a card.", "The fold is the side of the frame.", "Do not cut yet."),
      },
      {
        title: "Draw",
        minutes: "3 min",
        visual: "frame-draw",
        body: c("On the front only, draw a rectangle. Leave a fat border.", "Do not draw on the back leaf.", "A skinny border will buckle."),
      },
      {
        title: "Window",
        minutes: "4 min",
        visual: "frame-window",
        body: c("Cut out that rectangle. That is the window.", "Cut the front leaf only.", "If you cut both leaves, start a new sheet."),
      },
      {
        title: "Three sides",
        minutes: "4 min",
        visual: "frame-glue",
        body: c("Glue the front to the back on three sides. Leave one side open.", "The open side is where the picture slides in.", "Glue on all four sides traps the picture."),
      },
      {
        title: "Stand",
        minutes: "4 min",
        visual: "frame-stand",
        body: c("Fold a triangle from leftover. Glue it to the back so the frame leans.", "A lean, not straight up.", "A straight stand tips."),
      },
      {
        title: "Ten seconds",
        minutes: "3 min",
        visual: "iterate",
        body: c("Slide a drawing in. Hands off. Count to ten.", "If it falls, look at the stand.", "A frame that only works in your hands did not pass."),
      },
    ],
    vocab: [
      { term: "window", meaning: "The hole you look through at the picture", es: "ventana" },
      { term: "easel", meaning: "The stand that leans the frame", es: "caballete" },
      { term: "lip", meaning: "The edge that keeps the picture from falling out", es: "labio / reborde" },
    ],
    ell: "Cut a window. Glue three sides. Fold a stand. Slide the picture. Hands off. Count ten.",
    sped: "Pre-cut window. Student glues three sides and the stand. Tape easel if glue peels.",
    ta: "Do not hold the frame during the count. Catch it if it tips, then they rebuild the stand.",
    plan: {
      hook: "A drawing that cannot stand is still a drawing. A frame is the product that shows it.",
      objectives: ["Cut a window with a sound border.", "Build a free-standing easel.", "Load a picture and pass 10 s."],
      assessment: ["Hands-off 10 s.", "Picture stays.", "Fail mode named if it falls."],
      snags: ["Cutting both leaves.", "Vertical stand that tips.", "Glue on the picture."],
      extend: "A hanging frame with a leftover-strip handle. Compare stand vs. hang.",
    },
  },
  {
    id: "flower",
    name: "Standing flower",
    family: "fold",
    teConcept: "Kirigami as manufacturing: one cut becomes every petal; a rolled stem is a column",
    grades: "2–6",
    time: "25–35 min",
    materials: ["1 sheet", "scissors"],
    mst: ["TR", "ED", "HT"],
    blurb: c(
      "Fold, cut once, open — many petals. Roll the leftover into a stem. It has to stand.",
      "One folded cut makes every petal. The leftover strip rolls into a column stem. Stands 10 s in a cup of scrap or on its own roll.",
      "A repeating cut is a manufacturing process. The stem’s slenderness is a structure problem, same as the tower.",
    ),
    challenge: "A flower that stands for a count of 10. Point to the same cut in every petal.",
    spec: "Pass: stands 10 s, 4 or more petals from one folded cut. Stretch: a leaf from leftover, or two stacked layers.",
    steps: [
      {
        title: "Square",
        minutes: "3 min",
        visual: "square-cut",
        body: c("Fold a short edge onto a long edge. Cut the strip. Open the square. Keep the strip.", "The strip becomes the stem.", "A rectangle makes uneven petals."),
      },
      {
        title: "Fan",
        minutes: "3 min",
        visual: "flower-fan",
        body: c("Fold the square in half. Fold it in half again. Fold it in half one more time.", "A small packet. The open edges are the petals.", "Even folds make even petals."),
      },
      {
        title: "One cut",
        minutes: "4 min",
        visual: "flower-cut",
        body: c("Cut a petal shape on the open edge. Do not cut the folded spine all the way off.", "One cut through all the layers.", "If you cut the spine off, you get scraps, not a flower."),
      },
      {
        title: "Open",
        minutes: "3 min",
        visual: "flower-open",
        body: c("Open it gently. The same shape should show on every petal.", "Point to the cut on two petals.", "A jagged cut repeats on every petal."),
      },
      {
        title: "Stem",
        minutes: "4 min",
        visual: "flower-stand",
        body: c("Roll the leftover strip tight. Glue it to the back. Stand it up. Count to ten.", "A tight roll stands. A loose roll flops.", "Hands off for the count."),
      },
      {
        title: "One change",
        minutes: "3 min",
        visual: "iterate",
        body: c("If it flops, roll the stem tighter or make it shorter. Count to ten again.", "One change.", "A shorter stem stands more easily."),
      },
    ],
    vocab: [
      { term: "petal", meaning: "One of the matching parts around the flower", es: "pétalo" },
      { term: "hub", meaning: "The middle that holds every petal", es: "centro" },
      { term: "column", meaning: "The rolled stem that stands", es: "columna" },
    ],
    ell: "Square. Fold a packet. One cut. Open. Same shape every petal. Roll a stem. Count ten.",
    sped: "Pre-folded packet, teacher-marked cut line. Student cuts, opens, and stands. A bottle cap as a base.",
    ta: "If they cut the hub, they get separate petals — call it data, then a second packet. Do not tape it into a fake flower for them.",
    plan: {
      hook: "One cut, many petals. That is manufacturing, not magic.",
      objectives: ["Produce radial copies from one cut.", "Stand a rolled-stem flower 10 s.", "Point to the repeating cut."],
      assessment: ["Stands 10 s.", "Oral: show the same cut on two petals.", "Leftover used as stem, not trash."],
      snags: ["Cutting the hub.", "Floppy unrolled stem.", "Throwing the leftover."],
      extend: "Two-layer flower (two packets, offset). Compare fullness vs. time.",
    },
  },
  {
    id: "grabber",
    name: "Paper grabber",
    family: "move",
    teConcept: "A lever pair: squeeze is input, a hinge is the fulcrum, grip is output",
    grades: "4–8",
    time: "30–40 min",
    materials: ["1 sheet", "scissors", "1 paper fastener or a rolled-paper rivet", "an eraser as the load"],
    mst: ["TS", "ED", "TR"],
    blurb: c(
      "Fold two arms. Join them with a fastener. Squeeze. Pick up an eraser and walk it one meter.",
      "Tongs are a class 3 lever pair. Input at the handles, fulcrum at the fastener, output at the tips. 1 m carry, 2 of 3.",
      "Mechanical advantage is poor on purpose — you feel the force. Tip shape and hinge play are the parameters.",
    ),
    challenge: "Pick up an eraser and carry it 1 m without dropping, 2 of 3 trials. Tips away from faces.",
    spec: "Pass: 1 m carry, 2 of 3, eraser only. Stretch: a glue stick (rounder, heavier) or a 2 m carry.",
    steps: [
      {
        title: "Two arms",
        minutes: "8 min",
        visual: "grabber-arms",
        body: c(
          "Cut the sheet in half the long way. Fold each half into a stiff strip — like a thin beam.",
          "Two long strips. Accordion or a tight roll-flatten so each arm is a beam, not a noodle.",
          "Bending stiffness of the arms matters. A floppy arm dissipates your squeeze before the tip.",
        ),
      },
      {
        title: "Hinge",
        minutes: "8 min",
        visual: "grabber-hinge",
        body: c(
          "Stack the arms so they cross like a V. Push a fastener through both, a little below the top. The arms must scissor.",
          "Fulcrum near the handle end (class 3) or nearer the tips (class 1 tongs). Leave play so they rotate. A rolled-paper rivet if fasteners are out.",
          "Hinge location is the design choice. Sketch two: power vs. opening width.",
        ),
        tip: c("Not tight.", "If they will not scissor, the fastener is cinched.", "Count fasteners in and out."),
      },
      {
        title: "Grip",
        minutes: "6 min",
        visual: "grabber-grip",
        body: c(
          "Fold a little lip at each tip so the eraser cannot squirt out. Squeeze. Lift. Hold a count of three.",
          "Add a folded lip or a notch at the tips. Desk lift, 3 s. If it slips, the tip geometry failed, not “you.”",
          "Contact geometry: a notch is a fixture; a flat tip is friction only. Predict which holds a round glue stick.",
        ),
      },
      {
        title: "Carry test",
        minutes: "6 min",
        visual: "grabber-carry",
        body: c(
          "Pick up the eraser. Walk the tape. Tips away from faces. Two of three.",
          "1 m, 2 of 3. Record drop vs. peel vs. hinge flop. Same eraser every trial.",
          "A walk is a dynamic load. A desk lift is static. The spec is the walk.",
        ),
      },
      {
        title: "Tip or hinge",
        minutes: "6 min",
        visual: "iterate",
        body: c(
          "If it dropped, change the tips or move the fastener. Three more carries.",
          "One change aimed at the fail. Retest 2 of 3.",
          "You may trade opening width for grip. A grabber that only holds a flat eraser is a narrower product.",
        ),
      },
    ],
    vocab: [
      { term: "lever", meaning: "A bar that turns on a point to move a load", es: "palanca" },
      { term: "fulcrum", meaning: "The hinge the arms turn on", es: "punto de apoyo" },
      { term: "grip", meaning: "How the tips hold the eraser", es: "agarre" },
    ],
    ell: "Two stiff arms. Fastener. Squeeze. Lip on the tips. Pick up the eraser. Walk. Do not point at faces.",
    sped: "Pre-folded arms. Student only sets the fastener and tests. Desk-lift 3 s as the accessible spec.",
    ta: "Tips down and away. You may set the fastener. They squeeze and walk. Do not pinch the eraser “to help.”",
    plan: {
      hook: "A robot claw is this, in metal. We will pick up an eraser with paper.",
      objectives: ["Build a scissor grabber.", "Name fulcrum, input, output.", "Pass a 1 m carry 2 of 3."],
      assessment: ["2 of 3 carries.", "Oral IPO.", "A named change after a drop."],
      snags: ["Pointing at faces.", "Cinched hinge.", "Floppy un-beamed arms."],
      extend: "Pick up a glue stick. Report what tip change made round objects possible.",
    },
  },
  {
    id: "whirligig",
    name: "Whirligig",
    family: "move",
    teConcept: "A folk rotor: pull-relax on a twisted string stores energy and returns a spin",
    grades: "2–6",
    time: "20–30 min",
    materials: ["1 sheet (two disks)", "scissors", "glue stick", "about 60 cm of string or yarn"],
    mst: ["TS", "TR", "HT", "ED"],
    blurb: c(
      "Two paper disks, a string through the middle. Twirl. Pull. It spins. Count to five.",
      "A whirligig is a string-drive rotor. Twist, then pull-relax. Spin for a slow count of 5, 2 of 3. History: a toy older than printers.",
      "Energy store is the twisted string. Pull converts torsion to rotation. Friction at the holes is a loss — hole size is a parameter.",
    ),
    challenge: "Spin for a slow count of 5, 2 of 3 trials. Fingers in the loops — string never around a neck.",
    spec: "Pass: 5 s of visible spin, 2 of 3. Stretch: different pictures on each face that blur into one (a thaumatrope).",
    steps: [
      {
        title: "Two disks",
        minutes: "6 min",
        visual: "whirly-disk",
        body: c(
          "Cut two circles about the size of your palm. Glue them back to back. Let the glue grab.",
          "Two disks, same size. Glue, press. A heavier rotor stores more — a third scrap layer is allowed if you name it.",
          "Polar moment: more mass at the rim keeps spin. A tiny disk dies fast. Predict, then compare if time.",
        ),
      },
      {
        title: "String",
        minutes: "6 min",
        visual: "whirly-string",
        body: c(
          "Poke two holes near the middle, a finger apart. Thread the string through both and tie the ends into two loops.",
          "Two holes on a diameter, ~2 cm apart. String through both so the disk sits in the middle. Loops for fingers, not necks.",
          "Hole spacing is a parameter. Too close and it wobbles; too far and it will not wind.",
        ),
        tip: c("Loops for fingers.", "Teacher punches holes if poking is hard.", "Count how much string leaves the desk."),
      },
      {
        title: "Wind and pull",
        minutes: "8 min",
        visual: "whirly-spin",
        body: c(
          "Twirl the disk until the string winds. Pull your hands apart, then ease in. It should spin and wind the other way. Count five.",
          "Prime with a twirl. Then: pull (spin), relax (it rewinds), pull. Rhythm is the control. Three trials, count the spin.",
          "Input: work against torsion. Output: rotation. A dead whirligig is usually a slipped knot or a torn hole — diagnose.",
        ),
      },
      {
        title: "Faces",
        minutes: "6 min",
        visual: "iterate",
        body: c(
          "Draw a bird on one face and a cage on the other — or any two halves of a picture. Spin. Do they become one?",
          "Thaumatrope stretch: two complementary drawings. If the blur reads as one image, the rotor is fast enough.",
          "Persistence of vision is the user interface. History of moving pictures starts with toys like this.",
        ),
      },
    ],
    vocab: [
      { term: "rotor", meaning: "The disk that spins", es: "rotor" },
      { term: "twist", meaning: "Winding the string so it stores a pull", es: "torsión" },
      { term: "whirligig", meaning: "An old spinning toy on a string", es: "zumbel / matamoscas" },
    ],
    ell: "Two circles glued. Two holes. String. Loops on fingers. Twirl. Pull. Count five. Never on a neck.",
    sped: "Pre-cut disks, pre-punched holes. Student threads, winds, and counts. Larger disks are easier to see.",
    ta: "String stays on the desk until the test. Loops on fingers. If they wind it around a wrist, stop and redo the loops.",
    plan: {
      hook: "Before screens, a spinning paper disk was a moving picture.",
      objectives: ["Build a string-drive rotor.", "Sustain a 5 s spin.", "Name pull as the input and spin as the output."],
      assessment: ["2 of 3 spins of 5 s.", "Oral IPO.", "Safe loops, not a wrap."],
      snags: ["String around a neck or wrist.", "One hole instead of two.", "Glue still wet."],
      extend: "Rim-weighted disk vs. plain. Which spins longer?",
    },
  },
  {
    id: "berty",
    name: "Bertybot",
    family: "make",
    teConcept: "A cube-net foldable: the pixel head is a cross of six squares, tabs inside, then a body so he stands",
    grades: "3–8",
    time: "35–45 min",
    materials: ["1 sheet", "pencil", "scissors", "glue stick"],
    mst: ["ED", "TR", "HT"],
    blurb: c(
      "Draw Berty’s head net. Cut the outside. Fold the lines. Glue the tabs inside. Then give him a body so he stands.",
      "The head is a cube net: face in the middle, top, bottom, left, right, and back. Tabs tuck inside. The face stays out.",
      "Same manufacturing as the net cube. The pixel face is a label on one face. Limbs are a second assembly.",
    ),
    challenge: "A cube head with the face on the outside and the tabs inside. He stands for a count of 10.",
    spec: "Six squares, face out, tabs hidden, antenna on top, body and four strips so he stands 10 s.",
    steps: [
      {
        title: "The face",
        minutes: "4 min",
        visual: "berty-face",
        body: c(
          "Draw a square about four fingers wide. Draw two eyes. Draw a smile. This square is the face.",
          "The face is the front of the cube. Leave space around it on the sheet.",
          "Match the picture: two eyes, a smile. Do not fill the whole square.",
        ),
      },
      {
        title: "Top and bottom",
        minutes: "3 min",
        visual: "berty-updown",
        body: c(
          "Draw one square above the face. The same size. Draw one square below the face. The same size.",
          "Three squares in a column. The face is the middle one.",
          "If a square is bigger, the cube will not close.",
        ),
      },
      {
        title: "Sides and back",
        minutes: "4 min",
        visual: "berty-sides",
        body: c(
          "Draw one square to the left of the face. Draw one square to the right of the face. Draw one more square to the right of that.",
          "Count the squares. You need six.",
          "The last square is the back of the head.",
        ),
      },
      {
        title: "Glue tabs",
        minutes: "3 min",
        visual: "berty-tabs",
        body: c(
          "Draw a small triangle on the top edge. Draw one on the bottom edge. Draw one on the far left edge. Draw one on the far right edge.",
          "Four triangles. They are the glue tabs.",
          "Tabs stay small. A big tab will not tuck in.",
        ),
      },
      {
        title: "Cut the outside",
        minutes: "4 min",
        visual: "berty-cut",
        body: c(
          "Cut around the outside of the shape. Do not cut the lines between the squares.",
          "The outside is the cut. The inside lines are folds.",
          "If you cut between two squares, tape that cut and keep going.",
        ),
      },
      {
        title: "Fold",
        minutes: "4 min",
        visual: "berty-fold",
        body: c(
          "Fold on every line between squares. The face stays on the outside. Fold each triangle in.",
          "Crease every edge. Open it back up so you can glue.",
          "If the face is inside, unfold and flip the folds.",
        ),
      },
      {
        title: "Glue",
        minutes: "5 min",
        visual: "berty-glue",
        body: c(
          "Put glue on the triangles. Tuck them inside the cube. Press. Wait. The face looks out.",
          "One tab at a time. Glue inside, not on the face.",
          "A gap means a tab missed an edge. Open that side and tuck it.",
        ),
      },
      {
        title: "Antenna",
        minutes: "3 min",
        visual: "berty-antenna",
        body: c(
          "Fold a tiny scrap. Glue it on the top of the head. That is the antenna.",
          "A small triangle is enough.",
          "The antenna is on the top square, not on the face.",
        ),
      },
      {
        title: "Body",
        minutes: "4 min",
        visual: "berty-torso",
        body: c(
          "Fold a leftover rectangle into a thick body. Glue the head on top of it.",
          "The body is wider than it is deep. Press until the glue holds.",
          "The face still looks forward.",
        ),
      },
      {
        title: "Stand",
        minutes: "5 min",
        visual: "berty-stand",
        body: c(
          "Glue two strips at the sides for arms. Glue two strips under the body for legs. Stand him up. Hands off. Count to ten.",
          "Four strips. Arms at the shoulders. Legs under the body.",
          "Write an alias on the back if you want. No legal name.",
        ),
      },
    ],
    vocab: [
      { term: "net", meaning: "The flat shape that folds into the head", es: "desarrollo" },
      { term: "tab", meaning: "The triangle you glue inside", es: "pestaña" },
    ],
    ell: "Six squares. Face in the middle. Cut the outside. Fold the lines. Glue the tabs inside. Antenna on top. Body. Arms. Legs. Count ten.",
    sped: "Teacher draws the six squares. Student draws the face, cuts the outside, and folds. Tape instead of glue if the stick mashes.",
    ta: "Do not cut the lines between squares. If the face ends up inside, that is a fix, not a new sheet.",
    plan: {
      hook: "Berty on the home page is a paper cube. This is the net he folds up from.",
      objectives: ["Draw a six-square head net with the face marked.", "Cut the outline and fold the creases.", "Glue tabs inside and stand him up."],
      assessment: ["Face is on the outside.", "Tabs are inside.", "He stands for 10 seconds."],
      snags: ["Cutting between the squares.", "Glue on the face.", "Five squares instead of six."],
      extend: "A second, smaller head. Same net, half the size.",
    },
  },
];
