import type { Lab } from "./labs";

const c = (easy: string, classText: string, stretch: string) => ({
  easy,
  class: classText,
  stretch,
});

export const MORE_LABS: Lab[] = [
  {
    id: "boat",
    name: "Paper boat",
    family: "hold",
    teConcept: "Displacement and a floating hull: a folded vessel holds a load until it ships water",
    grades: "2–6",
    time: "25–35 min",
    materials: ["1 sheet", "paperclips or pennies as load", "shallow tray of water"],
    mst: ["ED", "TS", "TR", "IT"],
    blurb: c(
      "Fold a boat. Float it. Add clips one at a time. Count how many before it sinks.",
      "A hull is a container for air and load. Add mass one clip at a time. The last dry count is the score.",
      "Displacement: the boat sinks when load plus hull exceeds the weight of water pushed aside. Craftsmanship (dry creases) is a waterproofing process.",
    ),
    challenge: "Carry the most dry paperclips for 10 seconds. No tape on the hull.",
    spec: "Float 10 s with a recorded load. Stretch: beat the class median without adding tape.",
    steps: [
      {
        title: "Fold the hull",
        minutes: "8 min",
        visual: "boat-fold",
        body: c(
          "Fold in half like a book, then the top corners in, then the bottom flaps up. Pull the middle open into a boat.",
          "Classic newspaper boat: book fold, corners to a point, brim flaps up, open the center into a hull. Press seams so they stay dry.",
          "Every crease is a potential leak. Sharp, even folds are a joining process that does not use adhesive.",
        ),
      },
      {
        title: "Launch",
        minutes: "4 min",
        visual: "boat-float",
        body: c(
          "Set the boat in the tray. Hands off. Count to ten. If it sits, you have a hull.",
          "Free-float 10 s with no load. A boat that leans is a trim problem — mass is not centered.",
          "A control: empty hull first. If the empty boat ships water, the process failed before the load test.",
        ),
      },
      {
        title: "Load test",
        minutes: "8 min",
        visual: "boat-load",
        body: c(
          "Add one clip at a time in the middle. Count. Stop when water comes in.",
          "Add clips at midships, one at a time. Record the last dry count. A clip on the rim is a different test.",
          "Payload vs. reserve buoyancy. List fail mode: list, swamp, or crease leak.",
        ),
      },
      {
        title: "One change",
        minutes: "8 min",
        visual: "iterate",
        body: c(
          "Fold a second boat with tighter creases, or a taller side. Load again. Did the number go up?",
          "v2: taller gunwale or a double-folded bottom. Same clips. Compare.",
          "You changed freeboard or stiffness. Predict direction of change, then confirm.",
        ),
      },
    ],
    vocab: [
      { term: "hull", meaning: "The body of the boat that sits in the water", es: "casco" },
      { term: "load", meaning: "The clips you add", es: "carga" },
      { term: "sink", meaning: "Water comes in and the boat goes down", es: "hundirse" },
    ],
    ell: "Fold. Float. Add one clip. Count. Stop when water comes in.",
    sped: "Teacher folds v1. Student loads and counts. A yogurt lid as an alternate hull if fine-motor folding fails — then label it as a different material.",
    ta: "Do not hold the boat “steady” during the count. If it tips, that is data. Towels ready.",
    plan: {
      hook: "A flat sheet sinks. Folded, it carries metal. What did the process add?",
      objectives: [
        "Fold a free-floating hull.",
        "Run a counted load test.",
        "Name one process change that raised the score.",
      ],
      assessment: ["Empty-float 10 s.", "A load number.", "Fail mode named."],
      snags: ["Loading on the rim.", "Splashing as a joke.", "Tape on the hull without labeling it."],
      extend: "Compare letter vs. a leftover origami square as the blank.",
    },
  },
  {
    id: "catapult",
    name: "Paper catapult",
    family: "move",
    teConcept: "A lever stores a press and throws a light load — simple machine, distance spec",
    grades: "3–8",
    time: "35–45 min",
    materials: ["1–2 sheets", "tape (3 small pieces)", "pencil or dowel", "eraser as payload"],
    mst: ["ED", "TS", "TR", "MT"],
    blurb: c(
      "Fold an arm. Tape it to a base. Press and let go. The eraser flies. Measure. Change the arm.",
      "A catapult is a lever plus stored energy. The spec is distance along the floor, not height. Payload is an eraser — never at people.",
      "Class 1 or 2 lever depending on fulcrum. Arm length and launch angle are parameters. Safety is a hard constraint, not a suggestion.",
    ),
    challenge: "Land the eraser past a 1 m tape line, 2 of 3 shots, after one documented change.",
    spec: "2 of 3 past 1 m. Payload = eraser only. No shots toward faces.",
    steps: [
      {
        title: "Safety spec",
        minutes: "3 min",
        visual: "catapult-safe",
        body: c(
          "We throw erasers at the floor tape. Never at people. If you aim at a face, you sit out the test.",
          "Constraint: payload is an eraser. Range is along the floor. A face is never a target.",
          "Impacts: a simple machine scales. The rule is the same as shop tools — energy goes where we aim.",
        ),
      },
      {
        title: "Base and fulcrum",
        minutes: "8 min",
        visual: "catapult-base",
        body: c(
          "Fold a thick base so it does not hop. A pencil across it is the fulcrum — the turning point.",
          "A multi-fold beam is the base. Tape a pencil as a fulcrum. The base must stay put when you fire.",
          "If the base jumps, energy went into the base, not the load. Mass the base or hold it with a book.",
        ),
      },
      {
        title: "The arm",
        minutes: "8 min",
        visual: "catapult-arm",
        body: c(
          "Fold a long strip into a stiff arm. Tape a tiny cup or fold a pocket for the eraser. Rest the arm on the pencil.",
          "Stiff arm (folded strip). Pocket at the throwing end. Tape the other end to the base behind the fulcrum, or hold it as a hinge.",
          "Mechanical advantage: a longer throwing end raises speed and lowers force. Predict before you cut a second arm.",
        ),
      },
      {
        title: "Range test",
        minutes: "8 min",
        visual: "catapult-test",
        body: c(
          "Press the arm. Let go. Mark the landing. Three times. Write the numbers.",
          "Three shots, same press. Partner marks. Median distance vs. the 1 m line.",
          "Hold press distance constant. A harder press is a new variable — name it if you change it.",
        ),
      },
      {
        title: "Change the arm",
        minutes: "8 min",
        visual: "iterate",
        body: c(
          "Make the arm longer, or add a little extra fold at the pocket. Three more shots.",
          "One variable: arm length or launch angle (a book under the base). Label v2.",
          "Tradeoff: a longer arm can whip and miss the pocket. Quality control on the pocket counts.",
        ),
      },
    ],
    vocab: [
      { term: "lever", meaning: "A bar that turns on a point to move a load", es: "palanca" },
      { term: "fulcrum", meaning: "The turning point (the pencil)", es: "fulcro" },
      { term: "payload", meaning: "The thing you throw (the eraser)", es: "carga útil" },
    ],
    ell: "Base. Pencil. Arm. Eraser in the pocket. Press. Let go. Mark. Never at people.",
    sped: "Pre-folded base. Student builds the arm and tests. Seated launches only. Shorter spec (50 cm).",
    ta: "You may tape the fulcrum. They press and release. Stand beside the range, not downrange.",
    plan: {
      hook: "A spoon and a pea is a catapult. Paper can be the spoon.",
      objectives: ["Build a lever launcher.", "Test range against a line.", "Change one parameter safely."],
      assessment: ["Six distances.", "Oral: lever, fulcrum, load.", "Zero face-aimed shots."],
      snags: ["Flicking with fingers instead of the arm.", "A bouncing base.", "Paperclip payload (too sharp)."],
      extend: "Graph arm length vs. median range for the table.",
    },
  },
  {
    id: "chute",
    name: "Paper parachute",
    family: "fly",
    teConcept: "Drag as a design choice: a canopy slows a falling load; area vs. mass",
    grades: "3–8",
    time: "30–40 min",
    materials: ["1 sheet", "scissors", "4 leftover strips or thread", "paperclip payload"],
    mst: ["ED", "TS", "TR", "IT"],
    blurb: c(
      "Cut a square. Tie four strips to the corners. Hang a clip. Drop. Count. Cut a bigger or smaller canopy.",
      "A parachute trades speed for time. Same drop height. Time the fall. Canopy area is the easy variable.",
      "Drag scales with area and shape. A hole in the canopy can reduce oscillation. Mass vs. area is the tradeoff.",
    ),
    challenge: "Longest hang time from a set height, 2 of 3 drops, after one change.",
    spec: "Three timed drops. v2 changes one variable. Report hang time up or down.",
    steps: [
      {
        title: "Canopy",
        minutes: "5 min",
        visual: "chute-canopy",
        body: c(
          "Cut a square from the sheet. Keep the leftover strips — those are the lines.",
          "Square canopy. Leftover rectangle becomes four equal lines. A circle canopy is a stretch cut.",
          "Area is length × width for a square. Write it. v2 will need a number to compare.",
        ),
      },
      {
        title: "Lines and load",
        minutes: "8 min",
        visual: "chute-lines",
        body: c(
          "Tape or tie a strip to each corner. Tie the four ends to one paperclip.",
          "Equal line length. A short line on one corner tilts the canopy and it dives.",
          "The payload is a concentrated mass. Lines are tension members. A loose tape joint is a fail.",
        ),
      },
      {
        title: "Drop test",
        minutes: "8 min",
        visual: "chute-drop",
        body: c(
          "Stand on a chair only if the teacher says so — or drop from the same high shelf. Count. Three times.",
          "Same height every drop. Partner counts. Record hang time and whether it swung or fell straight.",
          "Release with the canopy above the load. A crumpled dump is not a test of the design.",
        ),
      },
      {
        title: "Change area or a hole",
        minutes: "8 min",
        visual: "iterate",
        body: c(
          "Cut a smaller square, or cut a small hole in the middle. Drop three more times.",
          "One change: canopy area or a spill hole. Predict hang time. Test n=3.",
          "A spill hole can trade a little drag for a lot of stability. Name which spec you care about.",
        ),
      },
    ],
    vocab: [
      { term: "canopy", meaning: "The big square that catches air", es: "campana" },
      { term: "drag", meaning: "Air slowing the fall", es: "arrastre" },
      { term: "payload", meaning: "The clip hanging under", es: "carga útil" },
    ],
    ell: "Square. Four strings. Clip. Drop. Count. Change the square. Drop again.",
    sped: "Pre-cut canopy. Student tapes lines and drops. Teacher on the chair; student counts.",
    ta: "Same height — pick a tile. Do not toss it like a ball. Canopy up, then drop.",
    plan: {
      hook: "A copter spins. A chute just gets in the air’s way. Both are slow-fall systems.",
      objectives: ["Build a canopy-and-lines system.", "Time a controlled drop.", "Change area or a hole and report the direction of change."],
      assessment: ["Six times.", "A written area for v1.", "Straight vs. swing noted."],
      snags: ["Uneven lines.", "Throwing.", "Standing on chairs without a rule."],
      extend: "Class plot: canopy area vs. hang time.",
    },
  },
  {
    id: "balance",
    name: "Paper balance",
    family: "draw",
    teConcept: "A measuring instrument: equal-arm balance, fulcrum, and a fair test of mass",
    grades: "3–8",
    time: "30–40 min",
    materials: ["1 sheet", "pencil", "tape", "paperclips as masses"],
    mst: ["ED", "MT", "CT", "TS"],
    blurb: c(
      "Fold a beam. Balance it on a pencil. Put clips on both sides. When it sits level, the masses match.",
      "An equal-arm balance is a tool. Calibrate it with the beam empty. Then unknown vs. known clips.",
      "A measuring instrument needs a zero, a unit, and a method. If the fulcrum is off-center, every reading is a lie.",
    ),
    challenge: "Mass an unknown (eraser or crumpled wad) in paperclips, then check on a second balance.",
    spec: "Empty beam levels. Unknown reported in clips. A neighbor’s balance agrees within 1 clip.",
    steps: [
      {
        title: "The beam",
        minutes: "6 min",
        visual: "balance-beam",
        body: c(
          "Fold a long stiff strip. Mark the exact middle.",
          "Fold a multi-layer beam. Find center by folding end to end once — that crease is the datum.",
          "The mid-crease is a construction line. If you guess the center, the instrument is biased.",
        ),
      },
      {
        title: "Fulcrum",
        minutes: "5 min",
        visual: "balance-fulcrum",
        body: c(
          "Rest the middle on a pencil. The beam should sit almost level with nothing on it.",
          "Pencil in a book-notch or between two erasers so it cannot roll. Empty-beam zero: it should not flop to one side.",
          "Calibrate: if it lists, the fulcrum is not at the center of mass. Slide, do not add tape-mass yet.",
        ),
      },
      {
        title: "Pans",
        minutes: "6 min",
        visual: "balance-pans",
        body: c(
          "Fold two small squares as pans. Tape one at each end, the same way.",
          "Matching pans at matching distances. A pan closer to the fulcrum cheats.",
          "Moment = force × distance. Equal arms mean equal distances. Measure if you need to.",
        ),
      },
      {
        title: "Mass an unknown",
        minutes: "8 min",
        visual: "balance-test",
        body: c(
          "Unknown on the left. Add clips on the right until it sits level. That number is the mass in clips.",
          "Unknown vs. unit clips. Record. Swap sides as a check — the number should match.",
          "Repeatability: three trials. If they differ by more than 1, the fulcrum slipped.",
        ),
      },
      {
        title: "Check a neighbor",
        minutes: "5 min",
        visual: "system",
        body: c(
          "Mass the same unknown on a friend’s balance. Did you get the same number?",
          "Inter-instrument check. A difference of 1 clip is OK. A difference of 4 means a process error.",
          "Quality control on tools. Name which balance you trust and why — with a reason, not a feeling.",
        ),
      },
    ],
    vocab: [
      { term: "balance", meaning: "A tool that compares two masses", es: "balanza" },
      { term: "unit", meaning: "What you count (here: one paperclip)", es: "unidad" },
      { term: "calibrate", meaning: "Set the empty tool so it reads zero", es: "calibrar" },
    ],
    ell: "Mark the middle. Pencil under. Empty sits level. Unknown here. Clips there. Count.",
    sped: "Pre-folded beam with the center marked. Student places clips and reads. Large clips.",
    ta: "Do not “help level it” with a finger. If it lists, they slide the fulcrum.",
    plan: {
      hook: "A number with no tool is a guess. Today the tool is paper.",
      objectives: ["Build an equal-arm balance.", "Calibrate empty.", "Mass an unknown in a stated unit."],
      assessment: ["Empty zero.", "A clip count.", "Neighbor check within 1."],
      snags: ["Off-center fulcrum.", "Pans at different distances.", "Holding the beam."],
      extend: "Make a 2-clip “standard” and mass a third object.",
    },
  },
  {
    id: "chain",
    name: "Paper chain",
    family: "hold",
    teConcept: "Tension members: links in series, a weak-link fail, and a load spec",
    grades: "2–6",
    time: "25–35 min",
    materials: ["1–2 sheets", "scissors", "glue or tape", "a load (book or shoe)"],
    mst: ["TS", "TR", "ED", "MT"],
    blurb: c(
      "Cut strips. Make loops. Link them. Hang a load. When it breaks, find the weak loop. Make that loop better.",
      "A chain is a series system: one failed link fails the product. Count the links. Record the fail link.",
      "Series reliability. Joint process (glue vs. tape vs. slit-lock) is a materials choice. Quality control is watching the join, not the pretty loop.",
    ),
    challenge: "Hold a specified load (one shoe or a textbook) for 10 seconds from a chair back or hook.",
    spec: "10 s with the named load. After a break, identify the fail link and rebuild that joint.",
    steps: [
      {
        title: "Cut strips",
        minutes: "6 min",
        visual: "chain-cut",
        body: c(
          "Cut even strips the short way, about two fingers wide. You need eight or more.",
          "Consistent width. A skinny strip is a planned weak link unless you mean it.",
          "Cross-grain vs. long-grain: strips along the long edge are usually stronger. Test both if you have time.",
        ),
      },
      {
        title: "First loop",
        minutes: "4 min",
        visual: "chain-loop",
        body: c(
          "Glue or tape the first strip into a ring. Overlap a thumb-width. Press.",
          "Overlap is a joint. Too little overlap peels. Press until it holds — wet glue is not a test yet.",
          "The joint is the product. A pretty ring with a 2 mm overlap is a fail waiting.",
        ),
      },
      {
        title: "Link the rest",
        minutes: "8 min",
        visual: "chain-link",
        body: c(
          "Each new strip goes through the last ring, then you close it. Count the links.",
          "Series assembly. Number the links in pencil. When it fails you will know which number.",
          "A chain is only as strong as its weakest joint. Numbering is data collection, not decoration.",
        ),
      },
      {
        title: "Load test",
        minutes: "6 min",
        visual: "chain-load",
        body: c(
          "Hang the chain. Hang the load. Hands off. Count ten. If it breaks, look at which loop.",
          "Static load 10 s. Record pass/fail and fail-link number. Do not bounce the load.",
          "Fail mode: peel at the overlap, tear at a slit, or paper tensile through the strip.",
        ),
      },
      {
        title: "Rebuild the weak one",
        minutes: "6 min",
        visual: "iterate",
        body: c(
          "Make that one loop with a bigger overlap or a double strip. Test again.",
          "Repair the fail link only. Retest. Did you move the fail somewhere else?",
          "Optimization: doubling every link wastes material. Doubling the weak one is management of resources.",
        ),
      },
    ],
    vocab: [
      { term: "link", meaning: "One loop in the chain", es: "eslabón" },
      { term: "tension", meaning: "A pull that tries to stretch it", es: "tensión" },
      { term: "weak link", meaning: "The one that breaks first", es: "eslabón débil" },
    ],
    ell: "Cut strips. First ring. Next strip through. Close. Hang. Count ten. Which loop broke?",
    sped: "Pre-cut strips. Tape joints. Fewer links (4). A lighter load (glue stick).",
    ta: "Do not hold the load during the count. Catch it if it falls so it does not hit a foot.",
    plan: {
      hook: "One loop holds a little. A chain holds more — until one loop does not.",
      objectives: ["Assemble a numbered series of links.", "Load-test and name the fail link.", "Repair that joint and retest."],
      assessment: ["A chain of ≥6 links.", "Fail-link number or a 10 s pass.", "A rebuilt joint."],
      snags: ["Wet glue on the test.", "Bouncing the book.", "Unnumbered links."],
      extend: "Slit-and-lock links with no tape. Compare process cost.",
    },
  },
  {
    id: "envelope",
    name: "Locking envelope",
    family: "make",
    teConcept: "Packaging a message: a self-locking wrap, a fit spec, and a seal as a process",
    grades: "3–7",
    time: "25–35 min",
    materials: ["1 sheet", "a note card or half-sheet message"],
    mst: ["TR", "ED", "HT", "IT"],
    blurb: c(
      "Fold a wrapper around a note. Tuck a flap. No glue if you can lock it. Does the note stay in when you shake?",
      "An envelope is packaging for information. The product (the note) sets the size. A tuck is a fastener-free seal.",
      "Fit, protect, identify. A failed envelope dumps the product or needs tape — both are process costs. History: folded letters before gummed flaps.",
    ),
    challenge: "Hold a half-sheet note through a 10-shake test with no tape. Address the front.",
    spec: "10-shake hold. Note undamaged. Recipient name on the outside.",
    steps: [
      {
        title: "The product",
        minutes: "3 min",
        visual: "envelope-note",
        body: c(
          "Write a short note or a lab word. That is the product the package must hold.",
          "The note is the payload. Measure it. The wrap has to be larger on two sides and able to tuck.",
          "Packaging starts from the product, not from a cute fold you hope will fit.",
        ),
      },
      {
        title: "Wrap",
        minutes: "8 min",
        visual: "envelope-wrap",
        body: c(
          "Place the note on the sheet. Fold the long sides over it. Then fold the bottom up.",
          "Side flaps first, then a bottom pocket. Crease against the note so the fit is snug, not baggy.",
          "Too snug scuffs the note (a quality fail). Too baggy and the shake test dumps it.",
        ),
      },
      {
        title: "Tuck lock",
        minutes: "6 min",
        visual: "envelope-tuck",
        body: c(
          "Fold the top down. Tuck it into the pocket. No glue if it stays.",
          "The top flap tucks into the bottom pocket. If it will not tuck, the bottom fold was too shallow — unfold and redo.",
          "A tuck is a friction lock. Tape is allowed as v2 but must be labeled as a process change.",
        ),
      },
      {
        title: "Shake test",
        minutes: "4 min",
        visual: "envelope-shake",
        body: c(
          "Hold it over the desk. Shake ten times. Did the note stay?",
          "Ten shakes, same height. Pass/fail. If it fails, do not tape first — change a fold.",
          "A seal spec. Address the outside: who is it for? That is the user.",
        ),
      },
    ],
    vocab: [
      { term: "package", meaning: "A wrap that holds and protects a product", es: "paquete" },
      { term: "seal", meaning: "The lock that keeps it closed", es: "sello" },
      { term: "tuck", meaning: "A flap slid into a pocket", es: "meter" },
    ],
    ell: "Write a note. Fold sides. Fold bottom. Tuck top. Shake ten. Name on the front.",
    sped: "Larger note and a larger wrap. Tape-seal allowed if labeled. Partner does the shake, student watches the flap.",
    ta: "If the tuck will not go, they unfold — you do not finish the wrap and hand it back.",
    plan: {
      hook: "Mail is a technology. The fold is the machine that keeps a secret until a person opens it.",
      objectives: ["Package a note to a fit.", "Use a tuck lock.", "Pass a shake test and identify a user."],
      assessment: ["10-shake hold.", "A name on the outside.", "No hidden tape unless labeled."],
      snags: ["Tape first.", "A baggy wrap.", "Shaking over the floor."],
      extend: "A window cut so the name shows — kirigami on a package.",
    },
  },
  {
    id: "crane",
    name: "Origami crane",
    family: "fold",
    teConcept: "A traditional process: square blank, bases, and a living hinge product",
    grades: "4–8",
    time: "35–45 min",
    materials: ["1 sheet (cut to square)", "the leftover strip"],
    mst: ["TR", "HT", "ED", "CT"],
    blurb: c(
      "Cut a square. Fold a crane. The leftover strip is a bookmark. The crane is a process with a history.",
      "The crane is a sequence of named bases. Miss a mountain/valley and the head will not invert. History: a peace and gift object.",
      "A process document (this lab) is a computer model of folds. The paper still has to take the crease. Craftsmanship is reversible until you press.",
    ),
    challenge: "A crane that sits on the desk. Head inverted, not torn. Leftover strip named — bookmark or chain link.",
    spec: "Pass: sits, head inverted. Stretch: who is it for? That need is the spec.",
    steps: [
      {
        title: "Square the blank",
        minutes: "4 min",
        visual: "square-cut",
        body: c(
          "Fold a short edge onto a long edge. Cut off the extra strip. Open the square. Keep the strip.",
          "Same square process as the balloon. The strip is a named leftover — bookmark or chain link, not trash.",
          "A non-square crane is a different, worse product. Squaring is quality control.",
        ),
      },
      {
        title: "Square base",
        minutes: "8 min",
        visual: "crane-base",
        body: c(
          "Fold the square in half. Open it. Fold it in half the other way. Open it. Fold one corner to the opposite corner. Open it. Fold the other corners together. Open it. Push the sides in until you have a smaller square.",
          "Book folds and diagonals, then a square base (like a smaller square with pockets). If it will not sit flat, a crease is on the wrong side.",
          "The square base is a module. Many models share it. Naming the base is process vocabulary.",
        ),
        tip: c(
          "If it is a mess, unfold to the square and match the picture.",
          "Diagonals one side, books the other — same rule as the balloon.",
          "Wrong-side diagonals prevent the collapse. Check before you force it.",
        ),
      },
      {
        title: "Tail and neck",
        minutes: "10 min",
        visual: "crane-bird",
        body: c(
          "Fold both side corners to the middle line. Lift one point up. That is the neck. Lift the other point up. That is the tail.",
          "Narrow the sides, then pull two opposite points up. Invert a small head on one point. Stretch the wings.",
          "The head is an inside reverse fold — a living hinge. Forcing it tears; unfolding a little first is allowed.",
        ),
      },
      {
        title: "The product",
        minutes: "6 min",
        visual: "crane-done",
        body: c(
          "Fold a tiny head on the neck. Open the wings. Set it on the desk. It should sit. Write your alias on the leftover strip. No legal name.",
          "A crane that sits is a pass. A crane that will not puff slightly needs a gentler pull on the back.",
          "History: the crane as gift and as a peace object. Who is yours for? That is the need.",
        ),
      },
    ],
    vocab: [
      { term: "base", meaning: "A starting set of folds many models share", es: "base" },
      { term: "reverse fold", meaning: "Push a point inside itself to make a head", es: "pliegue invertido" },
    ],
    ell: "Square first. Small square with pockets. Two points up. Tiny head. Wings out.",
    sped: "Pre-creased square base. Student does neck, head, wings. A simpler flapping bird as an alternate product.",
    ta: "Do not complete the reverse-fold head for them on the first try. Unfold together, then they push.",
    plan: {
      hook: "A thousand cranes is a story about making as care. We will make one, well.",
      objectives: ["Cut a square with a named leftover.", "Fold a square base.", "Finish a sitting crane."],
      assessment: ["Sits on the desk.", "Head inverted, not torn.", "Strip reused or labeled waste."],
      snags: ["Forcing the head.", "Throwing the strip.", "Skipping the square."],
      extend: "Compare balloon cube vs. crane — same square, different process family.",
    },
  },
  {
    id: "flake",
    name: "Kirigami flake",
    family: "make",
    teConcept: "Cutting for symmetry: a folded blank becomes many copies of one design; manufacturing",
    grades: "2–6",
    time: "20–30 min",
    materials: ["1 sheet", "scissors"],
    mst: ["TR", "MT", "CT", "HT"],
    blurb: c(
      "Fold small. Cut shapes. Open. The cuts repeat. That is how a factory copies a design.",
      "Kirigami + radial folds. One cut becomes six or eight. You are manufacturing identical features.",
      "A die-cut in a factory is this idea in metal. Constraints: do not cut the folded spine completely or the product falls apart.",
    ),
    challenge: "One flake that stays in one piece, with a repeating cut you can point to in every sector.",
    spec: "Opens as one piece. A visitor can name the repeating shape without help.",
    steps: [
      {
        title: "Fold for copies",
        minutes: "6 min",
        visual: "flake-fold",
        body: c(
          "Start with a square. Fold in half, then in thirds like a pizza slice, as even as you can.",
          "Square → diagonal or book, then into six or eight stacked wedges. Even wedges make even copies.",
          "Angular division is a process. Uneven wedges are a tolerance problem — features will not match.",
        ),
      },
      {
        title: "Cut the design",
        minutes: "8 min",
        visual: "flake-cut",
        body: c(
          "Cut little shapes from the edges. Do not cut all the way across or it falls into bits.",
          "Remove triangles and half-circles from the open edges. Leave the folded spine connected in at least two places.",
          "You are subtracting material. The leftover is the product. Over-cutting is a scrap part.",
        ),
        tip: c(
          "Leave bridges of paper.",
          "If a piece falls off, that cut went through a bridge.",
          "A 4 mm bridge is safer than a 1 mm bridge on copy paper.",
        ),
      },
      {
        title: "Open and inspect",
        minutes: "5 min",
        visual: "flake-open",
        body: c(
          "Open gently. Count how many times your cut shows. That is the copy count.",
          "Unfold. Quality check: does each sector match? A mismatch is an uneven fold, not a bad scissor.",
          "Repeatability. If you folded six and see five, a wedge was lost to a through-cut.",
        ),
      },
      {
        title: "Name the process",
        minutes: "4 min",
        visual: "system",
        body: c(
          "One cut, many copies. Point to the shape that repeats.",
          "Input: one cut. Process: folded stack. Output: a ring of copies. That is manufacturing.",
          "A factory die does this in one hit. Your scissors are a slower tool for the same idea.",
        ),
      },
    ],
    vocab: [
      { term: "symmetry", meaning: "The same shape repeating around", es: "simetría" },
      { term: "copy", meaning: "The same cut showing again", es: "copia" },
      { term: "bridge", meaning: "A bit of paper you must leave so it stays one piece", es: "puente" },
    ],
    ell: "Fold small. Cut the edge. Do not cut through. Open. Count the copies.",
    sped: "Pre-folded wedge. Large cuts only. A teacher-held stack while they cut once.",
    ta: "If it falls to bits, the next sheet is the lesson — “leave a bridge” — not you cutting a perfect flake for the fridge.",
    plan: {
      hook: "A cookie cutter makes the same cookie. A folded cut makes the same hole, many times.",
      objectives: ["Fold a radial blank.", "Cut without separating the part.", "Name the repeating feature and the copy count."],
      assessment: ["One-piece flake.", "Copy count stated.", "A pointed repeating shape."],
      snags: ["Cutting the spine.", "Unfolding too fast and tearing.", "Calling it “just a snowflake” with no process word."],
      extend: "Two flakes, six-fold vs. eight-fold. Same cut, different copy count.",
    },
  },
  {
    id: "ramp",
    name: "Inclined plane",
    family: "move",
    teConcept: "Simple machine: a ramp trades distance for force; time an eraser down two slopes",
    grades: "3–8",
    time: "30–40 min",
    materials: ["1–2 sheets", "books for height", "eraser as the load", "tape optional"],
    mst: ["TS", "ED", "MT", "TR"],
    blurb: c(
      "Fold a stiff ramp. High end on a book. Slide an eraser. Make a longer, gentler ramp. Which is easier to start? Which is faster?",
      "An inclined plane trades a long path for a smaller force. Two ramps, same height, different length. Time the slide and talk effort.",
      "Work ≈ force × distance. A gentle ramp lowers force and raises distance. Speed is a different metric — pick one spec.",
    ),
    challenge: "Same start height. Two ramps. Report which needed less push to start, and which had the shorter slide time.",
    spec: "Two lengths, one height. A start-force observation and a time for each.",
    steps: [
      {
        title: "Stiff board",
        minutes: "6 min",
        visual: "ramp-fold",
        body: c(
          "Fold the sheet over and over into a stiff board. That is your ramp.",
          "Accordion or multi-fold beam so it does not sag. Sag is a different machine.",
          "A floppy sheet is a mechanism, not a plane. Stiffness is a materials-and-process requirement.",
        ),
      },
      {
        title: "Set the height",
        minutes: "4 min",
        visual: "ramp-set",
        body: c(
          "One end on a book. The other on the desk. That height stays the same all period.",
          "Lock the height (one book). Length will change, height will not — otherwise you changed two things.",
          "Controlled variable: rise. Independent variable: run. That is the experiment.",
        ),
      },
      {
        title: "Steep test",
        minutes: "6 min",
        visual: "ramp-steep",
        body: c(
          "Short ramp, steep hill. Let the eraser go. Count. Did you have to push?",
          "Three slides. Record time and whether it started by itself. A push is data, not a cheat, if you write it.",
          "A steep plane can become a drop. If it falls, the run is too short for this rise.",
        ),
      },
      {
        title: "Gentle test",
        minutes: "8 min",
        visual: "ramp-gentle",
        body: c(
          "Add a second sheet to make a longer ramp, same book. Try again. Easier to start? Slower ride?",
          "Same rise, longer run. Three slides. Compare start-force and time to the steep data.",
          "Tradeoff: less force, more distance, usually more time. Name which spec a wheelchair ramp optimizes.",
        ),
      },
      {
        title: "Name the machine",
        minutes: "4 min",
        visual: "system",
        body: c(
          "This is an inclined plane — a simple machine. Stairs and ramps in the hallway are the same idea.",
          "Input: a small push over a long path. Output: the load is up (or down) the same height.",
          "Connect to the catapult (lever) and the pinwheel (wheel and axle). Paper can model more than one machine.",
        ),
      },
    ],
    vocab: [
      { term: "inclined plane", meaning: "A ramp — a slope that helps move a load", es: "plano inclinado" },
      { term: "rise", meaning: "How tall the high end is", es: "altura" },
      { term: "run", meaning: "How long the ramp is", es: "largo" },
    ],
    ell: "Fold a board. Book under one end. Eraser slides. Count. Longer ramp, same book. Compare.",
    sped: "Pre-folded board. Student only sets and times. A toy car if the eraser sticks. Sit-down test.",
    ta: "Do not blow the eraser down. Gravity or a finger-push they admit on the paper.",
    plan: {
      hook: "Moving van ramps exist because lifting a sofa straight up is a worse machine for people.",
      objectives: ["Build a stiff inclined plane.", "Hold rise constant while changing run.", "Report a force/time tradeoff."],
      assessment: ["Two data rows.", "Height named as the same.", "Oral: ramp is a simple machine."],
      snags: ["Changing the book stack.", "A sagging sheet.", "Racing without writing times."],
      extend: "Add a fold-up lip as a curb — now it is a chute, a different system.",
    },
  },
  {
    id: "hat",
    name: "Paper hat",
    family: "make",
    teConcept: "A wearable product: fit as the spec, a user, and a brim as structure",
    grades: "2–6",
    time: "25–35 min",
    materials: ["1 sheet (larger paper helps — B or A3)", "tape optional"],
    mst: ["ED", "TR", "HT", "IT"],
    blurb: c(
      "Fold a hat. Put it on. Walk ten steps. If it stays, the fit passed. If it falls, change a fold.",
      "Wearables have a user. The spec is stay-on for a 10-step walk. Head size is a constraint you cannot change — the hat must.",
      "Anthropometry in paper: one sheet, many heads. A dart or a tape tab is a sizing process. Who is it for?",
    ),
    challenge: "Stays on for a 10-step walk, hands free. Optional: a brim that shades the eyes.",
    spec: "10-step walk, hands off. If it fails, one documented change, rewalk.",
    steps: [
      {
        title: "The user",
        minutes: "3 min",
        visual: "hat-user",
        body: c(
          "Who is the hat for — you, a partner, a stuffed mascot? Measure with a strip around the head.",
          "A leftover strip as a tape measure: wrap, mark, compare to the sheet. The product has a user.",
          "If the circumference is larger than the sheet’s useful brim, you need a join or a bigger sheet (B / A3).",
        ),
      },
      {
        title: "Fold the hat",
        minutes: "10 min",
        visual: "hat-fold",
        body: c(
          "Fold in half. Fold the top corners in. Fold the brim up on both sides. Open and try it.",
          "Classic newspaper hat: book fold, corners to a point, brim flaps. Try on early — a hat that only looks right on the desk is not a wearable.",
          "Try-on is a fit test in the make, not after. Tailors do this. So do we.",
        ),
      },
      {
        title: "Walk test",
        minutes: "5 min",
        visual: "hat-walk",
        body: c(
          "Hands off. Ten steps. Partner watches. Did it stay?",
          "10-step walk, same floor. Pass/fail. A hand on the hat is a fail.",
          "Dynamic fit. A hat that sits in a chair test can still fail a walk — inertia and nod.",
        ),
      },
      {
        title: "Size it",
        minutes: "8 min",
        visual: "iterate",
        body: c(
          "Too big: fold a deeper brim or add a tape tab inside. Too small: unfold a little. Walk again.",
          "One change aimed at the fail. A deeper brim shortens the opening. Tape is a process — label it.",
          "You cannot change the head. You change the product. That is human-centered design, small.",
        ),
      },
    ],
    vocab: [
      { term: "fit", meaning: "How well it matches the person", es: "ajuste" },
      { term: "brim", meaning: "The folded edge around the head", es: "ala" },
      { term: "user", meaning: "The person it is for", es: "usuario" },
    ],
    ell: "Who is it for? Fold. Put it on. Walk ten. Hands off. Change one fold. Walk again.",
    sped: "B or A3 paper. Partner as the user if sensory issues with headwear — the stuffed mascot is a valid user. Tape-tab sizing.",
    ta: "Do not hold the hat on during the walk. If it falls, they pick it up and change a fold.",
    plan: {
      hook: "A hat that looks right and falls off is a failed product. Fit is the spec.",
      objectives: ["Name a user and a head size.", "Fold a wearable.", "Pass a hands-free walk or iterate once."],
      assessment: ["A named user.", "Walk pass or a documented v2.", "Brim identified as structure."],
      snags: ["Hands on the hat.", "One sheet too small and no join.", "Decorating before a fit."],
      extend: "A chin strap from the leftover strip — a new subsystem.",
    },
  },
  {
    id: "mobius",
    name: "Möbius strip",
    family: "draw",
    teConcept: "An investigation: a half-twist makes one surface; cutting is a test, not a decoration",
    grades: "4–8",
    time: "20–30 min",
    materials: ["1 sheet cut into long strips", "tape", "pencil", "scissors"],
    mst: ["CT", "ED", "TS"],
    blurb: c(
      "Tape a loop with a twist. Draw a line. It comes back on “the other side.” Cut down the middle. Surprise — that is data.",
      "A Möbius strip is a model of a one-sided surface. Predict, then cut. A control loop (no twist) behaves differently.",
      "A thought you can hold. Computer models of topology start here. The cut is an experiment with a predicted vs. observed outcome.",
    ),
    challenge: "Three loops: 0 twist, 1 half-twist, 2 half-twists. Predict the cut, then cut.",
    spec: "A written prediction for each cut, then an observed result. Control included.",
    steps: [
      {
        title: "Control loop",
        minutes: "4 min",
        visual: "mobius-loop",
        body: c(
          "Tape a strip into a normal bracelet. No twist. Draw a line on one side. It stays on one side.",
          "Control: 0 twist. A line around returns to the start without visiting the other face.",
          "Without a control, the Möbius cut is a magic trick. Science and technology both want the control.",
        ),
      },
      {
        title: "Half twist",
        minutes: "5 min",
        visual: "mobius-twist",
        body: c(
          "New strip. Flip one end once. Tape. Draw a line without lifting the pencil. Keep going.",
          "One half-twist, then join. A single pencil line visits both “sides” and returns. One surface.",
          "The model is the product. If the tape mashed the twist out, you built the control again.",
        ),
      },
      {
        title: "Predict the cut",
        minutes: "3 min",
        visual: "mobius-predict",
        body: c(
          "Write: if I cut down the middle, I think I will get ___. Then cut.",
          "Prediction on paper before scissors. Options: two loops, one long loop, two linked loops.",
          "A hypothesis is cheap. Changing it after you see the cut is not data.",
        ),
      },
      {
        title: "Cut and compare",
        minutes: "8 min",
        visual: "mobius-cut",
        body: c(
          "Cut down the middle all the way. What did you get? Try a strip with two twists if you have time.",
          "Midline cut on the Möbius (usually one longer loop). Two half-twists usually give two linked loops. Record.",
          "Parameters: number of half-twists. The cut is a test of a geometric system, not a craft.",
        ),
      },
    ],
    vocab: [
      { term: "surface", meaning: "A side you can draw on", es: "superficie" },
      { term: "twist", meaning: "A flip in the strip before you tape it", es: "giro" },
      { term: "predict", meaning: "Write what you think will happen before you cut", es: "predecir" },
    ],
    ell: "Loop with no twist. Loop with one flip. Draw a line. Write a guess. Cut the middle. Look.",
    sped: "Pre-taped control and Möbius. Student only draws and cuts. Larger strips (half-sheet).",
    ta: "Do not tell them the surprise. The prediction is the thinking. Catch the pieces so they can compare.",
    plan: {
      hook: "A piece of paper has two sides — until a process changes that.",
      objectives: ["Build a control and a Möbius.", "Write a prediction.", "Cut and compare to the prediction."],
      assessment: ["Two models.", "A written guess dated before the cut.", "Observed result in a sentence."],
      snags: ["Telling the punchline first.", "No control.", "A mashed twist."],
      extend: "Third strip, two half-twists. Predict before they see anyone else’s.",
    },
  },
  {
    id: "cup",
    name: "Origami cup",
    family: "make",
    teConcept: "A vessel: folds make a container; a hold-water spec tests the process",
    grades: "3–7",
    time: "20–30 min",
    materials: ["1 square", "a few spoons of water", "a tray"],
    mst: ["TR", "ED", "TS", "IT"],
    blurb: c(
      "Fold a cup. Pour a little water. Count to thirty. If it leaks, the crease was the leak. Fold again, sharper.",
      "A cup is a container system. The spec is hold two spoons of water for 30 seconds. Crease quality is waterproofing.",
      "Paper is hydrophilic — it will fail if time is long. The lab is about process and a short spec, not a camping lie. Impacts: disposable vessels vs. a reuse cup.",
    ),
    challenge: "Hold two spoons of water for 30 seconds over a tray. No tape.",
    spec: "30 s, two spoons, no tape. A drip before 30 s is a fail — fold v2.",
    steps: [
      {
        title: "Square",
        minutes: "3 min",
        visual: "square-cut",
        body: c(
          "Make a square. Leftover strip stays dry — a coaster.",
          "Square blank. The leftover is a drip catcher, not trash.",
          "A rectangular cup is a different net. Square first.",
        ),
      },
      {
        title: "Fold the vessel",
        minutes: "8 min",
        visual: "cup-fold",
        body: c(
          "Fold a triangle. Fold the two side corners in. Fold the top flaps down, one each way. Open the pocket.",
          "Classic origami cup: diagonal, two corners to the centerline, two top flaps as locks. Open the mouth.",
          "The locks are folded fasteners. If a flap is not seated, that wall will wick first.",
        ),
      },
      {
        title: "Water spec",
        minutes: "6 min",
        visual: "cup-water",
        body: c(
          "Over a tray. Two spoons of water. Hands off the sides. Count to thirty. Look for a drip.",
          "Two spoons, 30 s, tray below. Pass/fail. Note where it leaked — a crease, a wall, or the bottom point.",
          "Fail location is the lesson. A bottom-point leak is a geometry issue; a wall leak is a crease issue.",
        ),
      },
      {
        title: "Sharpen or double",
        minutes: "6 min",
        visual: "iterate",
        body: c(
          "Dry your hands. Fold a second cup with harder creases. Test again.",
          "v2: sharper locks, or a slightly thicker paper (two layers on a wall). Same water spec.",
          "You will not beat physics forever — copy paper wets. Name the time limit as a constraint, not a moral failing.",
        ),
      },
    ],
    vocab: [
      { term: "vessel", meaning: "A container that holds a liquid", es: "vasija" },
      { term: "leak", meaning: "Water finding a way out", es: "fuga" },
      { term: "wick", meaning: "Water climbing through the paper", es: "absorber" },
    ],
    ell: "Fold a cup. Two spoons. Count thirty. If it drips, fold a new cup. Harder creases.",
    sped: "Pre-folded cup they only open and test. A plastic cup as the control “other material.” Fewer spoons (one).",
    ta: "Tray always. Do not hold the walls closed for them during the count. A fail is useful.",
    plan: {
      hook: "A cup from a sheet with no glue — then water tells you if the process worked.",
      objectives: ["Fold a locking cup.", "Test a hold-water spec over a tray.", "Connect a leak to a crease or a point."],
      assessment: ["A 30 s pass or a named leak location.", "v2 folded.", "Leftover used as a coaster."],
      snags: ["No tray.", "Filling from the sink (too much water).", "Tape on v1."],
      extend: "Waxed paper or a crayon rub as a coating — a materials upgrade, labeled.",
    },
  },
  {
    id: "beam",
    name: "Brick Beam Challenge",
    family: "hold",
    teConcept:
      "Engineering design under a kit constraint: a paper-and-stick structure spans the Testing Canyon so a hanging picture circle stays flat and free, then holds a brick",
    grades: "6–8",
    time: "45–50 min",
    materials: [
      "6 sheets of paper",
      "6 sticks",
      "36 in of tape (one yard — that is all)",
      "shop hanger: wood stick with the picture circle hanging on string",
      "bricks",
      "Testing Canyon Cart",
    ],
    mst: ["ED", "TR", "TS", "MT"],
    blurb: c(
      "Crew of 2 or 3. Cover a span — short or long. The shop stick sits on your structure. The picture circle hangs. It must stay flat and not touch the second shelf. Then it has to hold one brick.",
      "Form a crew. Name a Crew Leader. Using 6 sheets, 6 sticks, and 36\" of tape, cover either the short span or the wider long span. The picture circle hangs from the shop stick that rests on your work. Pass: circle hangs free (not touching the second shelf), stays flat, and holds 1 brick for 6–7 seconds. Extra bricks are the contest.",
      "You choose the span: a short gap lowers bending; the longer gap raises the moment. The hanger is a three-string platform. If your structure sags or twists, the circle tilts or lands on shelf 2 — both are fails. Tape is a scarce joining budget.",
    ),
    challenge:
      "Cover the short span or the longer span. The picture circle must hang free and stay flat, then hold 1 brick. Add bricks for the contest.",
    spec: "Pass: hanger stick on the structure, picture circle hangs freely (does not touch the second shelf), circle stays flat, 1 brick on the circle, hands off, 6–7 s. Contest: extra bricks, same count. Name the fail: sag, twist, tilt, shelf-touch, slip, or tape tear.",
    steps: [
      {
        title: "Form a crew",
        minutes: "4 min",
        visual: "beam-crew",
        body: c(
          "Find 2 or 3 people. Pick a Crew Leader for now. Who is absent today? Write the names.",
          "Crew of 2 or 3. Decide: who is Crew Leader for this period? Who is absent? The Leader calls the test. Everyone still builds.",
          "Roles are for the period, not forever. Leader = calls GO, records the count, watches the circle. Absent partners get a named job when they return: tester or sketcher.",
        ),
        tip: c(
          "A crew of one is allowed if the class is short. The teacher is not your third.",
          "Crew Leader is not “the only one who touches paper.” The Leader talks. Hands stay on the kit.",
          "If a student is out, do not wait. Build. Leave a labeled sketch so they can join the contest round.",
        ),
      },
      {
        title: "Read the cart",
        minutes: "6 min",
        visual: "beam-spans",
        body: c(
          "The top of the cart is a canyon. You may cover the short gap or the longer wider gap. Look at the shop stick: the picture circle hangs from it on string. That stick will sit on your structure.",
          "Two legal spans: the short distance, or the wider longer distance. Your structure only has to cover one. The shop hanger (wood stick + hanging picture circle) rests on what you make. The circle must hang in the air — it may not rest on the second shelf.",
          "Span is a design choice. Short span: smaller moment, easier pass. Long span: harder, more load path. Clearance is a constraint: string length is fixed, so sag or a low structure drops the circle onto shelf 2. Sketch the cart and mark which span you will take.",
        ),
        tip: c(
          "Walk to the cart. Point at the short gap. Point at the long gap. Point at the second shelf.",
          "Measure both spans with a stick or a sheet before you cut. Write the numbers on the sketch.",
          "The hanger is not yours to redesign. It is the load fixture. Your job is the span structure under it.",
        ),
      },
      {
        title: "Read the kit",
        minutes: "3 min",
        visual: "beam-kit",
        body: c(
          "Count: 6 papers. 6 sticks. 36 inches of tape — one yard, that is all. You may not borrow. You may make anything that covers the span.",
          "Constraints (musts): 6 sheets, 6 sticks, 36\" tape, no extra tape from the drawer. You may make a beam, beams, a truss, a platform — anything that covers the span you chose. Criteria: hang free, stay flat, hold 1 brick 6–7 s, then extra bricks.",
          "A yard of tape is a joining budget. Spend it on joints, not wrapping. Sticks are chords; paper is webbing, tubes, or flanges. Write the kit and the chosen span on the sketch before you cut.",
        ),
      },
      {
        title: "Two ideas",
        minutes: "6 min",
        visual: "beam-ideas",
        body: c(
          "Idea A: roll paper into tubes and tape sticks along them. Idea B: fold a tall zigzag. Draw both. Circle the one you will try. Mark short span or long span.",
          "Sketch an I-beam, rolled tubes, or a triangle truss. Depth (taller) usually beats more layers. Circle v1, mark short or long span, and say why in one sentence.",
          "Bending moment grows with span. A 3 cm tall I on the short gap will out-hold a pancake on the long gap. Predict fail mode: sag (circle drops to the shelf), twist (circle tilts), or hanger roll-off.",
        ),
      },
      {
        title: "Build v1",
        minutes: "14 min",
        visual: "beam-build",
        body: c(
          "Build the idea you circled. Save tape. The shop stick has to sit on it without rolling off. Practice the length on a desk gap first.",
          "Craftsmanship: even rolls, sharp folds, tape only at joints. Length must sit on both sides of the span plus a little extra. Leave a flat place on top for the hanger stick — a round tube will dump it.",
          "Quality control: a seat for the hanger, not a peak. If the top is round, add a paper saddle. Leave 4–6 in of tape unspent until after the first cart test.",
        ),
        tip: c(
          "Do not use all the tape on the first joint.",
          "Measure the span you chose before the last cut. Too short cannot be taped longer.",
          "A saddle (a folded paper trough) keeps the hanger from rolling. That is a feature, not extra decoration.",
        ),
      },
      {
        title: "Hang the circle",
        minutes: "8 min",
        visual: "beam-test",
        body: c(
          "Set your structure on the canyon. Set the shop stick on it. The picture circle hangs. Look: is it touching the second shelf? Is it flat? If yes and yes (free and flat), put ONE brick on the circle. Hands off. Count to seven.",
          "Order: structure on the span → hanger stick on the structure → picture circle hanging → check hang-free (air under the circle, not on shelf 2) → check flat → 1 brick on the circle → hands off → 6–7 s. Fail if the circle touches the shelf, tilts, or drops the brick. Nobody’s hands under the circle.",
          "The circle is a hanging platform. Tilt = torsion or an unlevel seat. Shelf-touch = too much sag or a structure that sits too low. A pass with a slight bounce is still a pass if it stays free, flat, and holds the brick for the count.",
        ),
      },
      {
        title: "Add bricks",
        minutes: "8 min",
        visual: "beam-contest",
        body: c(
          "If one brick held, add another. Count to seven again. The circle still has to hang free and stay flat. Keep going. Most bricks that stay wins.",
          "Contest: extra bricks, same 6–7 s, same hang-free and flat rules. One change allowed between bricks if you still have tape. Score = last brick that held the full count with the circle still free and flat.",
          "Stack vs. twist: a taller brick pile raises the center of mass on a hanging platform. A 2-brick pass that stays flat beats a 4-brick dump you cannot explain.",
        ),
      },
    ],
    vocab: [
      { term: "span", meaning: "The gap you cover — short, or the wider longer one", es: "tramo" },
      { term: "picture circle", meaning: "The round board that hangs from the shop stick", es: "círculo" },
      { term: "hanger", meaning: "The wood stick with string. It sits on your structure.", es: "colgador" },
      { term: "hang free", meaning: "The circle is in the air. It does not touch the second shelf.", es: "colgar libre" },
      { term: "flat", meaning: "The circle is level, not tipped", es: "plano / nivelado" },
    ],
    ell: "Cover a gap. Short or long. The stick sits on your work. The circle hangs. It must not touch the shelf. It must stay flat. Then one brick. Count seven.",
    sped: "Short span is the accessible path. Pre-rolled tubes they tape together. Teacher seats the hanger; student watches “free?” and “flat?” One-brick pass is the grade; contest is optional. Books on a desk circle if bricks are an IEP safety note.",
    ta: "Do not hold the hanger during the count. Ask: “Is the circle touching the shelf? Is it flat?” Hands never under the circle. Tape is theirs; do not fetch more.",
    plan: {
      hook: "The shop stick is not the structure. Your job is whatever it sits on — short span or long — so a hanging circle stays flat, free, and holds a brick.",
      objectives: [
        "Form a crew of 2–3 and name a Crew Leader.",
        "Choose the short span or the wider long span and design under kit constraints (6 sheets, 6 sticks, 36\" tape).",
        "Seat the shop hanger so the picture circle hangs free (not touching the second shelf) and stays flat.",
        "Hold 1 brick on the circle for 6–7 seconds; name a fail mode; add bricks for the contest if it passed.",
      ],
      assessment: [
        "Crew names, Leader, and chosen span on the sketch.",
        "Two idea sketches, one circled.",
        "Hang-free and flat checked before the brick.",
        "Pass/fail on 1 brick × 6–7 s, fail mode named.",
        "Contest score = last brick that held with the circle still free and flat.",
      ],
      snags: [
        "Using the whole yard of tape on the first joint.",
        "Structure too short for the span they marked.",
        "Round top — hanger rolls off.",
        "Circle resting on the second shelf (sag or a low build).",
        "Circle tilted — they still put a brick on it.",
        "Hands under the circle “to be safe.”",
        "Borrowing tape from another crew.",
      ],
      extend:
        "Same kit on the long span after a short-span pass. Photograph the seat under the hanger and label saddle, web, and joint.",
    },
  },
];
