import type { HubLang } from "@/lib/hub-lang";

/** Step lines for the Start unit. fa-AF, rw, and ti need a native check. */
const rows: [string, string, string, string, string, string, string, string][] = [
  ["Make a square", "Зроби квадрат", "Сделай квадрат", "Haz un cuadrado", "اصنع مربعًا", "مربع بساز", "Kora kare", "ርቡዕ ግበር"],
  ["Fold a short edge onto a long edge", "Склади короткий край на довгий", "Сложи короткий край на длинный", "Dobla un lado corto sobre un lado largo", "اطوِ الحافة القصيرة على الطويلة", "لبه کوتاه را روی لبه بلند تا کن", "Zinga uruhande rugufi ku rurerure", "ሓጺር ወሰን ኣብ ነዊሕ ዓጽፍ"],
  ["Cut the leftover strip", "Відріж зайву смужку", "Отрежь лишнюю полоску", "Corta la tira que sobra", "قص الشريط الزائد", "نوار اضافه را ببر", "Kata akarongo gasigaye", "ዝተረፈ ስትሪፕ ቑረጽ"],
  ["Open it. You have a square", "Розгорни. Маєш квадрат", "Разверни. У тебя квадрат", "Ábrelo. Tienes un cuadrado", "افتحها. صار معك مربع", "باز کن. مربع داری", "Fungura. Ufite kare", "ክፈቶ። ርቡዕ ኣለካ"],
  ["Plus, then X", "Плюс, потім хрест", "Плюс, потом крест", "Más, luego X", "زائد ثم إكس", "جمع، بعد ضربدر", "Plus, hanyuma X", "ፕላስ፣ ድሕሪኡ X"],
  ["Fold the top edge to the bottom edge. Open it", "Склади верхній край до нижнього. Розгорни", "Сложи верхний край к нижнему. Разверни", "Dobla el borde de arriba al de abajo. Ábrelo", "اطوِ الحافة العليا إلى السفلى. افتحها", "لبه بالا را به پایین تا کن. باز کن", "Zinga hejuru ku hepfo. Fungura", "ላዕለዋይ ወሰን ናብ ታሕቲ ዓጽፍ። ክፈቶ"],
  ["Fold the left edge to the right edge. Open it", "Склади лівий край до правого. Розгорни", "Сложи левый край к правому. Разверни", "Dobla el borde izquierdo al derecho. Ábrelo", "اطوِ الحافة اليسرى إلى اليمنى. افتحها", "لبه چپ را به راست تا کن. باز کن", "Zinga ibumoso ku buryo. Fungura", "ጸጋማይ ወሰን ናብ የማን ዓጽፍ። ክፈቶ"],
  ["Fold one corner to the opposite corner. Open it", "Склади кут до протилежного кута. Розгорни", "Сложи угол к противоположному. Разверни", "Dobla una esquina a la opuesta. Ábrelo", "اطوِ زاوية إلى الزاوية المقابلة. افتحها", "یک گوشه را به گوشه روبه‌رو تا کن. باز کن", "Zinga uruhande ku rundi. Fungura", "ሓደ ኩርናዕ ናብ ካልእ ዓጽፍ። ክፈቶ"],
  ["Fold the other corners together. Open it", "Склади інші кути разом. Розгорни", "Сложи другие углы вместе. Разверни", "Dobla las otras esquinas juntas. Ábrelo", "اطوِ الزاويتين الأخريين معًا. افتحها", "گوشه‌های دیگر را با هم تا کن. باز کن", "Zinga izindi mpande hamwe. Fungura", "ኻልኦት ኩርናዓት ዓጽፍ። ክፈቶ"],
  ["Small triangle", "Малий трикутник", "Маленький треугольник", "Triángulo pequeño", "مثلث صغير", "سه‌گوش کوچک", "Mpandeshatu ntoya", "ንእሽቶ ስሉስ ኩርናዕ"],
  ["Pinch the middle of each side", "Защипни середину кожного боку", "Зажми середину каждой стороны", "Pellizca el medio de cada lado", "اقرص منتصف كل ضلع", "وسط هر ضلع را نیشگون بگیر", "Kamira hagati ya buruhande", "ማእከል ነፍሲ ወከፍ ጎኒ ጸቕጥ"],
  ["Let the paper fall into a small triangle", "Нехай папір ляже малим трикутником", "Пусть бумага ляжет маленьким треугольником", "Deja que el papel caiga en un triángulo pequeño", "دع الورق يسقط مثلثًا صغيرًا", "بگذار کاغذ سه‌گوش کوچک شود", "Reka impapuro igwe nk'impandeshatu ntoya", "ወረቐት ንእሽቶ ስሉስ ኩርናዕ ይኹን"],
  ["If it will not fall, unfold. The X and the plus must be on opposite sides", "Якщо не лягає, розгорни. Хрест і плюс мають бути з різних боків", "Если не ложится, разверни. Крест и плюс должны быть с разных сторон", "Si no cae, desdóblalo. La X y el más van en lados opuestos", "إن لم يسقط، افتحه. الإكس والزائد على جهتين مختلفتين", "اگر نیفتاد، باز کن. ضربدر و جمع باید در دو روی مختلف باشند", "Niba itagwa, fungura. X na plus bigomba kuba ku mpande zitandukanye", "እንተዘይወዲቑ፡ ክፈቶ። Xን ፕላስን ኣብ ዝተፈላለዩ ጎኒ"],
  ["Corners up", "Кути вгору", "Углы вверх", "Esquinas arriba", "الزوايا للأعلى", "گوشه‌ها بالا", "Impande hejuru", "ኩርናዓት ንላዕሊ"],
  ["Fold the left corner of the top layer up to the top point", "Склади лівий кут верхнього шару до верхньої точки", "Сложи левый угол верхнего слоя к верхней точке", "Dobla la esquina izquierda de la capa de arriba hasta la punta", "اطوِ الزاوية اليسرى للطبقة العليا إلى الرأس", "گوشه چپ لایه بالا را تا نوک تا کن", "Zinga uruhande rw'ibumoso rw'igice cyo hejuru ku mutwe", "ጸጋማይ ኩርናዕ ናይ ላዕለዋይ ንብራቕ ናብ ርእሲ ዓጽፍ"],
  ["Fold the right corner of the top layer up to the top point", "Склади правий кут верхнього шару до верхньої точки", "Сложи правый угол верхнего слоя к верхней точке", "Dobla la esquina derecha de la capa de arriba hasta la punta", "اطوِ الزاوية اليمنى للطبقة العليا إلى الرأس", "گوشه راست لایه بالا را تا نوک تا کن", "Zinga uruhande rw'iburyo rw'igice cyo hejuru ku mutwe", "የማናይ ኩርናዕ ናይ ላዕለዋይ ንብራቕ ናብ ርእሲ ዓጽፍ"],
  ["Turn it over", "Переверни", "Переверни", "Dale la vuelta", "اقلبه", "برگردان", "Hinduliza", "ገልብጦ"],
  ["Fold the two corners up on this side too", "Склади два кути вгору і з цього боку", "Сложи два угла вверх и с этой стороны", "Dobla las dos esquinas hacia arriba también en este lado", "اطوِ الزاويتين للأعلى في هذا الوجه أيضًا", "در این رو هم دو گوشه را بالا تا کن", "Zinga impande ebyiri hejuru no kuri uru ruhande", "ኣብዚ ጎኒ እውን ክልተ ኩርናዓት ንላዕሊ ዓጽፍ"],
  ["Pockets", "Кишені", "Карманы", "Bolsillos", "جيوب", "جیب‌ها", "Amasakoshi", "ኪስ"],
  ["Fold the left side corner to the center", "Склади лівий бічний кут до центру", "Сложи левый боковой угол к центру", "Dobla la esquina izquierda al centro", "اطوِ زاوية اليسار إلى الوسط", "گوشه چپ را به وسط تا کن", "Zinga uruhande rw'ibumoso hagati", "ጸጋማይ ኩርናዕ ናብ ማእከል ዓጽፍ"],
  ["Fold the right side corner to the center", "Склади правий бічний кут до центру", "Сложи правый боковой угол к центру", "Dobla la esquina derecha al centro", "اطوِ زاوية اليمين إلى الوسط", "گوشه راست را به وسط تا کن", "Zinga uruhande rw'iburyo hagati", "የማናይ ኩርናዕ ናብ ማእከል ዓጽፍ"],
  ["Fold the two side corners to the center on this side", "Склади два бічні кути до центру з цього боку", "Сложи два боковых угла к центру с этой стороны", "Dobla las dos esquinas laterales al centro en este lado", "اطوِ زاويتي الجانب إلى الوسط في هذا الوجه", "در این رو دو گوشه کنار را به وسط تا کن", "Zinga impande z'impera ebyiri hagati kuri uru ruhande", "ኣብዚ ጎኒ ክልተ ኩርናዓት ናብ ማእከል ዓጽፍ"],
  ["Tuck and blow", "Заправ і дмухни", "Заправь и подуй", "Mete y sopla", "أدخل وانفخ", "بگذار و فوت کن", "Shyira uhuhe", "ኣእቱ እሞ ንፋስ"],
  ["Tuck one small flap into a pocket", "Заправ один маленький клапан у кишеню", "Заправь один маленький клапан в карман", "Mete una solapa pequeña en un bolsillo", "أدخل لسانًا صغيرًا في جيب", "یک زبانه کوچک را در جیب بگذار", "Shyira uruhande ruto mu gisakoshi", "ሓደ ንእሽቶ ናይ ወረቐት ኣብ ኪስ ኣእቱ"],
  ["Tuck the other three flaps", "Заправ інші три клапани", "Заправь остальные три клапана", "Mete las otras tres solapas", "أدخل الألسنة الثلاثة الأخرى", "سه زبانه دیگر را بگذار", "Shyira andi mato atatu", "ኻልኦት ሰለስተ ኣእቱ"],
  ["Find the hole at the bottom", "Знайди дірку знизу", "Найди дырку снизу", "Busca el agujero de abajo", "جد الثقب في الأسفل", "سوراخ پایین را پیدا کن", "Shaka umwobo hepfo", "ዓንቂ ኣብ ታሕቲ ርኸብ"],
  ["Blow once, slow", "Дмухни один раз, повільно", "Подуй один раз, медленно", "Sopla una vez, despacio", "انفخ مرة، ببطء", "یک بار آهسته فوت کن", "Huha rimwe, buhoro", "ሓንሳእ ቀስ ኢልካ ንፋስ"],
  ["No glue. It should puff into a cube", "Без клею. Має надутися в куб", "Без клея. Должен надуться в куб", "Sin pegamento. Debe inflarse en un cubo", "بلا صمغ. ينتفخ مكعبًا", "بی چسب. باید مکعب باد شود", "Nta kol. Igomba kwivuvura nk'ikibe", "ኣይኮነን ሙጫ። ኩብ ይንፋሕ"],
  ["Cut a square", "Виріж квадрат", "Вырежи квадрат", "Corta un cuadrado", "قص مربعًا", "مربع ببر", "Kata kare", "ርቡዕ ቑረጽ"],
  ["Cuts to the center", "Розрізи до центру", "Разрезы к центру", "Cortes hacia el centro", "قصّات إلى الوسط", "برش تا وسط", "Gukata kugera hagati", "ቑረጽ ናብ ማእከል"],
  ["Every other point", "Кожен другий кут", "Каждый второй угол", "Una esquina sí y otra no", "كل زاوية ثانية", "یک گوشه در میان", "Impande zirimo n'iziri", "ሓደ ኩርናዕ ገዲፍካ"],
  ["Axle", "Вісь", "Ось", "Eje", "محور", "محور", "Ikinyobwa", "ኣኽስ"],
  ["Test the system", "Перевір систему", "Проверь систему", "Prueba el sistema", "جرّب النظام", "سامانه را بیازما", "Gerageza sisitemu", "ስርዓት ፈትን"],
  ["Open", "Розгорни", "Разверни", "Abre", "افتح", "باز کن", "Fungura", "ክፈት"],
  ["Square", "Квадрат", "Квадрат", "Cuadrado", "مربع", "مربع", "Kare", "ርቡዕ"],
  ["Draw two light lines corner to corner", "Накресли дві легкі лінії від кута до кута", "Нарисуй две легкие линии от угла к углу", "Dibuja dos líneas ligeras de esquina a esquina", "ارسم خطين خفيفين من زاوية إلى زاوية", "دو خط سبک از گوشه به گوشه بکش", "Shushanya imirongo ibiri yoroheje kuva ku mpande", "ክልተ ቀለልቲ መስመራት ካብ ኩርናዕ ናብ ኩርናዕ ስኣል"],
  ["Cut along each, but stop before the middle", "Ріж уздовж кожної, але спинись перед серединою", "Режь вдоль каждой, но остановись перед серединой", "Corta por cada una, pero para antes del medio", "قص على كل خط، وتوقف قبل الوسط", "روی هر کدام ببر، ولی پیش از وسط بایست", "Kata kuri buri murongo, hagarara imbere yo hagati", "ኣብ ነፍሲ ወከፍ ቑረጽ፣ ቅድሚ ማእከል ደው ኢልካ"],
  ["Take every other corner point to the middle", "Кожен другий кут склади до середини", "Каждый второй угол сложи к середине", "Lleva una esquina sí y otra no al centro", "خذ كل زاوية ثانية إلى الوسط", "یک گوشه در میان را به وسط بیاور", "Zana impande zirimo n'iziri hagati", "ሓደ ኩርናዕ ገዲፍካ ናብ ማእከል ኣምጽእ"],
  ["Four points stacked", "Чотири кінці один на одному", "Четыре конца друг на друге", "Cuatro puntas apiladas", "أربع رؤوس فوق بعضها", "چهار نوک روی هم", "Utuntu tune ku rundi", "ኣርባዕተ ነጥብታት ደርቢዮም"],
  ["Hold them", "Тримай їх", "Держи их", "Sujétalas", "أمسكها", "نگه‌شان دار", "Zibifate", "ሓዝዎም"],
  ["A pushpin through the stack into the pencil eraser", "Канцелярська кнопка крізь стос у гумку олівця", "Кнопка сквозь стопку в ластик карандаша", "Un alfiler por el montón hasta la goma del lápiz", "دبوس عبر الكومة إلى ممحاة القلم", "سنجاق از توده تا پاک‌کن مداد", "Umusumari unyura mu rutonde kugera ku gomu y'ikaramu", "መርፍእ ብመደብ ናብ ምድምዳም ኣእቱ"],
  ["Not tight", "Не туго", "Не туго", "No apretado", "ليس مشدودًا", "سفت نباشد", "Ntabwo bikaze", "ኣይጠበቕ"],
  ["The wheel must wiggle a little", "Колесо має трохи хитатися", "Колесо должно чуть болтаться", "La rueda debe moverse un poco", "يجب أن تهتز العجلة قليلًا", "چرخ باید کمی لق باشد", "Uruziga rugomba kunyeganyega gato", "መንኰርኰር ቁሩብ ይንቀጥቀጥ"],
  ["Blow straight at it", "Дмухай прямо на нього", "Дуй прямо на него", "Sopla de frente", "انفخ نحوه مباشرة", "مستقیم به آن فوت کن", "Huha imbere", "ብቐጥታ ንፋስ"],
  ["If it does not spin, the pin is too tight", "Якщо не крутиться, кнопка занадто туга", "Если не крутится, кнопка слишком тугая", "Si no gira, el alfiler está muy apretado", "إن لم يدر، الدبوس مشدود جدًا", "اگر نچرخید، سنجاق بیش از حد سفت است", "Niba itazunguruka, umusumari ukaze cyane", "እንተዘይዘወረ፡ መርፍእ ኣዝዩ ጠቢቑ"],
  ["Loosen", "Послаб", "Ослабь", "Aflójalo", "أرخِه", "شل کن", "Rekura", "ፈትሖ"],
  ["Who", "Для кого", "Для кого", "Para quién", "لمن", "برای کی", "Ninde", "መን"],
  ["In half", "Навпіл", "Пополам", "Por la mitad", "إلى النصف", "از وسط", "Kabiri", "ኣብ ፍርቂ"],
  ["Corners", "Кути", "Углы", "Esquinas", "زوايا", "گوشه‌ها", "Impande", "ኩርናዓት"],
  ["Brim", "Поля", "Поля", "Ala", "حافة", "لبه", "Urusyo", "ወሰን"],
  ["Walk", "Хода", "Ходьба", "Camina", "امشِ", "راه برو", "Genda", "እየ"],
  ["One change", "Одна зміна", "Одно изменение", "Un cambio", "تغيير واحد", "یک تغییر", "Impinduka imwe", "ሓደ ለውጢ"],
  ["Name who the hat is for", "Назви, для кого капелюх", "Назови, для кого шляпа", "Di para quién es el gorro", "سمِّ لمن القبعة", "بگو کلاه برای کیست", "Vuga uwo ingofero iriho", "ኮፍያ ንመን ምዃና በል"],
  ["Wrap a strip around the head", "Обмотай смужку навколо голови", "Оберни полоску вокруг головы", "Envuelve una tira alrededor de la cabeza", "لفّ شريطًا حول الرأس", "نواری را دور سر بپیچ", "Zinga akarongo ku mutwe", "ስትሪፕ ኣብ ርእሲ ከበብ"],
  ["That length is the size", "Ця довжина і є розмір", "Эта длина и есть размер", "Esa longitud es la talla", "هذا الطول هو المقاس", "این درازا اندازه است", "Uburebure ni ingano", "እቲ ንውሓት መጠን እዩ"],
  ["Fold the top edge down to the bottom edge", "Склади верхній край до нижнього", "Сложи верхний край к нижнему", "Dobla el borde de arriba hasta el de abajo", "اطوِ الحافة العليا إلى السفلى", "لبه بالا را تا پایین تا کن", "Zinga uruhande rwo hejuru kugera hepfo", "ላዕለዋይ ወሰን ናብ ታሕቲ ዓጽፍ"],
  ["Fold the top left corner down to the middle", "Склади верхній лівий кут до середини", "Сложи верхний левый угол к середине", "Dobla la esquina superior izquierda al centro", "اطوِ الزاوية اليسرى العليا إلى الوسط", "گوشه چپ بالا را به وسط تا کن", "Zinga uruhande rw'ibumoso rwo hejuru hagati", "ላዕለዋይ ጸጋማይ ኩርናዕ ናብ ማእከል ዓጽፍ"],
  ["Fold the top right corner down to the middle", "Склади верхній правий кут до середини", "Сложи верхний правый угол к середине", "Dobla la esquina superior derecha al centro", "اطوِ الزاوية اليمنى العليا إلى الوسط", "گوشه راست بالا را به وسط تا کن", "Zinga uruhande rw'iburyo rwo hejuru hagati", "ላዕለዋይ የማናይ ኩርናዕ ናብ ማእከል ዓጽፍ"],
  ["Fold the bottom strip up", "Склади нижню смужку вгору", "Сложи нижнюю полоску вверх", "Dobla la tira de abajo hacia arriba", "اطوِ الشريط السفلي للأعلى", "نوار پایین را بالا تا کن", "Zinga akarongo ko hepfo hejuru", "ታሕታይ ስትሪፕ ንላዕሊ ዓጽፍ"],
  ["Turn the hat over", "Переверни капелюх", "Переверни шляпу", "Dale la vuelta al gorro", "اقلب القبعة", "کلاه را برگردان", "Hinduliza ingofero", "ኮፍያ ገልብጥ"],
  ["Fold the other bottom strip up", "Склади другу нижню смужку вгору", "Сложи другую нижнюю полоску вверх", "Dobla la otra tira de abajo hacia arriba", "اطوِ الشريط السفلي الآخر للأعلى", "نوار پایین دیگر را بالا تا کن", "Zinga akandi karongo ko hepfo hejuru", "ኻልእ ታሕታይ ስትሪፕ ንላዕሊ ዓጽፍ"],
  ["Open the bottom a little", "Трохи розкрий низ", "Чуть раскрой низ", "Abre un poco la parte de abajo", "افتح الأسفل قليلًا", "پایین را کمی باز کن", "Fungura hepfo gato", "ታሕቲ ቁሩብ ክፈት"],
  ["Put the hat on", "Надінь капелюх", "Надень шляпу", "Ponte el gorro", "ضع القبعة", "کلاه را بگذار", "Iyambike ingofero", "ኮፍያ ኣእቱ"],
  ["Hands off", "Руки геть", "Руки прочь", "Manos fuera", "ارفع يديك", "دست‌ها را بردار", "Kuraho amaboko", "ኢድካ ኣልዕል"],
  ["Walk ten steps", "Пройди десять кроків", "Пройди десять шагов", "Camina diez pasos", "امشِ عشر خطوات", "ده قدم راه برو", "Genda intambwe icumi", "ዓሰርተ ስጉምቲ እየ"],
  ["If it falls, fold a deeper brim", "Якщо падає, зроби глибші поля", "Если падает, сложи поля глубже", "Si se cae, dobla un ala más honda", "إن سقطت، اطوِ حافة أعمق", "اگر افتاد، لبه را عمیق‌تر تا کن", "Niba igwa, zinga urusyo rurerure", "እንተወዲቓ፡ ዓሚቕ ወሰን ዓጽፍ"],
  ["If it is tight, unfold a little", "Якщо тісно, трохи розгорни", "Если тесно, чуть разверни", "Si aprieta, desdóblalo un poco", "إن كانت ضيقة، افتحها قليلًا", "اگر تنگ است، کمی باز کن", "Niba ikaze, fungura gato", "እንተጠቢቑ፡ ቁሩብ ክፈት"],
  ["Walk ten steps again", "Пройди десять кроків ще раз", "Пройди десять шагов ещё раз", "Camina diez pasos otra vez", "امشِ عشر خطوات مرة أخرى", "دوباره ده قدم راه برو", "Ongera ugende intambwe icumi", "ደጊምካ ዓሰርተ ስጉምቲ እየ"],
  ["Triangle", "Трикутник", "Треугольник", "Triángulo", "مثلث", "سه‌گوش", "Mpandeshatu", "ስሉስ ኩርናዕ"],
  ["Side points", "Бічні кінці", "Боковые концы", "Puntas laterales", "رأسا الجانب", "نوک‌های کنار", "Utuntu tw'impera", "ኩርናዓት ጎኒ"],
  ["Two flaps", "Два клапани", "Два клапана", "Dos solapas", "لسانان", "دو زبانه", "Amato abiri", "ክልተ ናይ ወረቐት"],
  ["Water", "Вода", "Вода", "Agua", "ماء", "آب", "Amazi", "ማይ"],
  ["Open the square", "Розгорни квадрат", "Разверни квадрат", "Abre el cuadrado", "افتح المربع", "مربع را باز کن", "Fungura kare", "ርቡዕ ክፈት"],
  ["Keep the strip dry", "Тримай смужку сухою", "Держи полоску сухой", "Mantén la tira seca", "أبقِ الشريط جافًا", "نوار را خشک نگه دار", "Bika akarongo kayumye", "ስትሪፕ ደረቕ ግደፎ"],
  ["Fold the square in half, corner to opposite corner", "Склади квадрат навпіл, кут до протилежного", "Сложи квадрат пополам, угол к противоположному", "Dobla el cuadrado por la mitad, esquina a esquina", "اطوِ المربع نصفين، من زاوية إلى المقابلة", "مربع را از گوشه به گوشه تا کن", "Zinga kare kabiri, uruhande ku rundi", "ርቡዕ ኣብ ፍርቂ፡ ኩርናዕ ናብ ኩርናዕ ዓጽፍ"],
  ["The point is up", "Кінчик угорі", "Остриё сверху", "La punta arriba", "الرأس للأعلى", "نوک بالاست", "Umutwe uri hejuru", "ርእሲ ንላዕሊ"],
  ["Fold the left point up to the top point", "Склади лівий кінець до верхнього", "Сложи левый конец к верхнему", "Dobla la punta izquierda hasta la de arriba", "اطوِ الرأس الأيسر إلى الرأس العلوي", "نوک چپ را تا نوک بالا تا کن", "Zinga utuntu tw'ibumoso ku mutwe", "ጸጋማይ ነጥቢ ናብ ላዕለዋይ ዓጽፍ"],
  ["Fold the right point up to the top point", "Склади правий кінець до верхнього", "Сложи правый конец к верхнему", "Dobla la punta derecha hasta la de arriba", "اطوِ الرأس الأيمن إلى الرأس العلوي", "نوک راست را تا نوک بالا تا کن", "Zinga utuntu tw'iburyo ku mutwe", "የማናይ ነጥቢ ናብ ላዕለዋይ ዓጽፍ"],
  ["Fold the front flap down", "Склади передній клапан униз", "Сложи передний клапан вниз", "Dobla la solapa de delante hacia abajo", "اطوِ اللسان الأمامي للأسفل", "زبانه جلو را پایین تا کن", "Zinga uruhande rw'imbere hasi", "ቅድሚት ናይ ወረቐት ንታሕቲ ዓጽፍ"],
  ["Turn the cup over", "Переверни чашку", "Переверни чашку", "Dale la vuelta al vaso", "اقلب الكوب", "لیوان را برگردان", "Hinduliza igikombe", "ጽዋዕ ገልብጥ"],
  ["Fold the other flap down", "Склади другий клапан униз", "Сложи другой клапан вниз", "Dobla la otra solapa hacia abajo", "اطوِ اللسان الآخر للأسفل", "زبانه دیگر را پایین تا کن", "Zinga urundi ruhande hasi", "ኻልእ ናይ ወረቐት ንታሕቲ ዓጽፍ"],
  ["Open the pocket at the top", "Розкрий кишеню зверху", "Раскрой карман сверху", "Abre el bolsillo de arriba", "افتح الجيب من الأعلى", "جیب بالا را باز کن", "Fungura igisakoshi cyo hejuru", "ኪስ ኣብ ላዕሊ ክፈት"],
  ["This is the cup", "Це і є чашка", "Это и есть чашка", "Este es el vaso", "هذا هو الكوب", "این لیوان است", "Iki ni igikombe", "እዚ ጽዋዕ እዩ"],
  ["Hold it over a tray", "Тримай над тацею", "Держи над подносом", "Sosténlo sobre una bandeja", "أمسكه فوق صينية", "آن را روی سینی نگه دار", "Gibifate hejuru y'agatebe", "ኣብ ልዕሊ ታብላ ሓዝ"],
  ["Pour in two spoons of water", "Налий дві ложки води", "Налей две ложки воды", "Echa dos cucharadas de agua", "صب ملعقتين من الماء", "دو قاشق آب بریز", "Suka amazi y'ama spoon abiri", "ክልተ ማንካ ማይ ኣእቱ"],
  ["Count to thirty", "Порахуй до тридцяти", "Сосчитай до тридцати", "Cuenta hasta treinta", "عُدّ إلى ثلاثين", "تا سی بشمار", "Bara kugeza kuri mirongo itatu", "ክሳብ ሰላሳ ቑጸር"],
  ["Look for a drip", "Шукай краплю", "Ищи каплю", "Busca una gota", "ابحث عن قطرة", "دنبال چکه بگرد", "Shaka itone", "ንጣብ ርአ"],
  ["Dry your hands", "Висуши руки", "Вытри руки", "Sécate las manos", "جفف يديك", "دست‌هایت را خشک کن", "Yumya ibiganza", "ኢድካ ኣንጽፍ"],
  ["Fold a second cup", "Склади другу чашку", "Сложи вторую чашку", "Dobla un segundo vaso", "اطوِ كوبًا ثانيًا", "لیوان دوم را تا کن", "Zinga igikombe cya kabiri", "ካልኣይ ጽዋዕ ዓጽፍ"],
  ["Press every crease harder", "Сильніше притисни кожен згин", "Сильнее прижми каждый сгиб", "Aprieta cada pliegue más fuerte", "اضغط كل ثنية أقوى", "هر تا را محکم‌تر فشار بده", "Kanda buri muzingo cyane", "ነፍሲ ወከፍ መስመር ብዓቢ ጸቕጥ"],
  ["Test again", "Перевір знову", "Проверь снова", "Prueba otra vez", "اختبر مرة أخرى", "دوباره بیازما", "Ongera ugerageze", "ደጊምካ ፈትን"],
  ["Inflate a closed cube with no glue. One slow breath. Name the leftover strip — bookmark, not trash.", "Надуй закритий куб без клею. Один повільний видих. Назви зайву смужку — закладка, не сміття.", "Надуй закрытый куб без клея. Один медленный выдох. Назови лишнюю полоску — закладка, не мусор.", "Infla un cubo cerrado sin pegamento. Un soplo lento. Nombra la tira — marcapáginas, no basura.", "انفخ مكعبًا مغلقًا بلا صمغ. نَفَس بطيء. سمِّ الشريط — فاصل كتاب، لا قمامة.", "مکعب بسته را بی چسب باد کن. یک فوت آهسته. نوار را نشانه‌گذار بنام، نه آشغال.", "Vuvura ikibe gifunze nta kol. Umwuka umwe woroshye. Ita akarongo — ikimenyetso, si imyanda.", "ዕጹው ኩብ ብዘይ ሙጫ ንፋሕ። ሓደ ቀስ ንፋስ። ስትሪፕ መጽሓፍ ምልክት እዩ፡ ኣይኮነን ጎሓፍ።"],
  ["It spins from one breath. If it does not, say if the pin is tight or the blades are wrong.", "Крутиться від одного видиху. Якщо ні — скажи, кнопка туга чи лопаті не ті.", "Крутится от одного выдоха. Если нет — скажи, кнопка тугая или лопасти не те.", "Gira con un soplo. Si no gira, di si el alfiler está apretado o las aspas están mal.", "يدور من نفخة واحدة. إن لم يدر، قل هل الدبوس مشدود أم الشفرات خطأ.", "با یک فوت می‌چرخد. اگر نچرخید، بگو سنجاق سفت است یا پره‌ها غلط‌اند.", "Izunguruka ku mwuka umwe. Niba itazunguruka, vuga niba umusumari ukaze cyangwa amabata atari yo.", "ብሓደ ንፋስ ይዘውር። እንተዘይዘወረ፡ መርፍእ ጠቢቑ ድዩ ኣስፋት ጌጋ በል።"],
  ["Stays on for a 10-step walk, hands free. Optional: a brim that shades the eyes.", "Тримається десять кроків, без рук. Можна: поля, що тінять очі.", "Держится десять шагов, без рук. Можно: поля, что тенят глаза.", "Se queda en una caminata de diez pasos, sin manos. Opcional: un ala que dé sombra.", "تبقى عشر خطوات واليدان حرتان. اختياري: حافة تظلّل العينين.", "ده قدم بی‌دست می‌ماند. دلخواه: لبه‌ای که چشم را سایه کند.", "Igumaho intambwe icumi, nta maboko. Ushobora: urusyo rwinshirira amaso.", "ዓሰርተ ስጉምቲ ብዘይ ኢድ ትጸንሕ። እንተደሊኻ፡ ንዓይኒ ዝሽፈን ወሰን።"],
  ["Hold two spoons of water for 30 seconds over a tray. No tape.", "Тримай дві ложки води 30 секунд над тацею. Без скотчу.", "Держи две ложки воды 30 секунд над подносом. Без скотча.", "Aguanta dos cucharadas de agua 30 segundos sobre una bandeja. Sin cinta.", "احمل ملعقتين ماء 30 ثانية فوق صينية. بلا شريط.", "دو قاشق آب را ۳۰ ثانیه روی سینی نگه دار. بی چسب.", "Gumya amazi y'ama spoon abiri amasegonda 30 hejuru y'agatebe. Nta riboni.", "ክልተ ማንካ ማይ ን30 ካልኢት ኣብ ልዕሊ ታብላ ሓዝ። ብዘይ ቴፕ።"],
];

function pack(index: number) {
  const out: Record<string, string> = {};
  for (const row of rows) out[row[0]] = row[index];
  return out;
}

export const START_LINES: Partial<Record<HubLang, Record<string, string>>> = {
  uk: pack(1),
  ru: pack(2),
  es: pack(3),
  ar: pack(4),
  "fa-AF": pack(5),
  rw: pack(6),
  ti: pack(7),
};
