/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildRouteImport } from './routes/build'
import { Route as DrawRouteImport } from './routes/draw'
import { Route as FoldRouteImport } from './routes/fold'
import { Route as FoldablesRouteImport } from './routes/foldables'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as MathRouteImport } from './routes/math'
import { Route as NetsRouteImport } from './routes/nets'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PrintRouteImport } from './routes/print'
import { Route as StandardsRouteImport } from './routes/standards'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SupportsRouteImport } from './routes/supports'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as FoldablesIndexRouteImport } from './routes/foldables.index'
import { Route as FoldablesIdRouteImport } from './routes/foldables.$id'
import { Route as LabsIndexRouteImport } from './routes/labs.index'
import { Route as LabsIdRouteImport } from './routes/labs.$id'
import { Route as PlansIndexRouteImport } from './routes/plans.index'
import { Route as PlansIdRouteImport } from './routes/plans.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawRoute = DrawRouteImport.update({
  id: '/draw',
  path: '/draw',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldRoute = FoldRouteImport.update({
  id: '/fold',
  path: '/fold',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldablesRoute = FoldablesRouteImport.update({
  id: '/foldables',
  path: '/foldables',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const MathRoute = MathRouteImport.update({
  id: '/math',
  path: '/math',
  getParentRoute: () => rootRouteImport,
} as any)
const NetsRoute = NetsRouteImport.update({
  id: '/nets',
  path: '/nets',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsRoute = StandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportsRoute = SupportsRouteImport.update({
  id: '/supports',
  path: '/supports',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldablesIndexRoute = FoldablesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FoldablesRoute,
} as any)
const FoldablesIdRoute = FoldablesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FoldablesRoute,
} as any)
const LabsIndexRoute = LabsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LabsRoute,
} as any)
const LabsIdRoute = LabsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LabsRoute,
} as any)
const PlansIndexRoute = PlansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlansRoute,
} as any)
const PlansIdRoute = PlansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PlansRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/draw': typeof DrawRoute
  '/fold': typeof FoldRoute
  '/foldables': typeof FoldablesRouteWithChildren
  '/labs': typeof LabsRouteWithChildren
  '/math': typeof MathRoute
  '/nets': typeof NetsRoute
  '/plans': typeof PlansRouteWithChildren
  '/print': typeof PrintRoute
  '/standards': typeof StandardsRoute
  '/studio': typeof StudioRoute
  '/supports': typeof SupportsRoute
  '/teacher': typeof TeacherRoute
  '/updates': typeof UpdatesRoute
  '/foldables/$id': typeof FoldablesIdRoute
  '/labs/$id': typeof LabsIdRoute
  '/plans/$id': typeof PlansIdRoute
  '/foldables/': typeof FoldablesIndexRoute
  '/labs/': typeof LabsIndexRoute
  '/plans/': typeof PlansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/draw': typeof DrawRoute
  '/fold': typeof FoldRoute
  '/math': typeof MathRoute
  '/nets': typeof NetsRoute
  '/print': typeof PrintRoute
  '/standards': typeof StandardsRoute
  '/studio': typeof StudioRoute
  '/supports': typeof SupportsRoute
  '/teacher': typeof TeacherRoute
  '/updates': typeof UpdatesRoute
  '/foldables/$id': typeof FoldablesIdRoute
  '/labs/$id': typeof LabsIdRoute
  '/plans/$id': typeof PlansIdRoute
  '/foldables': typeof FoldablesIndexRoute
  '/labs': typeof LabsIndexRoute
  '/plans': typeof PlansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/draw': typeof DrawRoute
  '/fold': typeof FoldRoute
  '/foldables': typeof FoldablesRouteWithChildren
  '/labs': typeof LabsRouteWithChildren
  '/math': typeof MathRoute
  '/nets': typeof NetsRoute
  '/plans': typeof PlansRouteWithChildren
  '/print': typeof PrintRoute
  '/standards': typeof StandardsRoute
  '/studio': typeof StudioRoute
  '/supports': typeof SupportsRoute
  '/teacher': typeof TeacherRoute
  '/updates': typeof UpdatesRoute
  '/foldables/$id': typeof FoldablesIdRoute
  '/labs/$id': typeof LabsIdRoute
  '/plans/$id': typeof PlansIdRoute
  '/foldables/': typeof FoldablesIndexRoute
  '/labs/': typeof LabsIndexRoute
  '/plans/': typeof PlansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/build'
    | '/draw'
    | '/fold'
    | '/foldables'
    | '/labs'
    | '/math'
    | '/nets'
    | '/plans'
    | '/print'
    | '/standards'
    | '/studio'
    | '/supports'
    | '/teacher'
    | '/updates'
    | '/foldables/$id'
    | '/labs/$id'
    | '/plans/$id'
    | '/foldables/'
    | '/labs/'
    | '/plans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/build'
    | '/draw'
    | '/fold'
    | '/math'
    | '/nets'
    | '/print'
    | '/standards'
    | '/studio'
    | '/supports'
    | '/teacher'
    | '/updates'
    | '/foldables/$id'
    | '/labs/$id'
    | '/plans/$id'
    | '/foldables'
    | '/labs'
    | '/plans'
  id:
    | '__root__'
    | '/'
    | '/build'
    | '/draw'
    | '/fold'
    | '/foldables'
    | '/labs'
    | '/math'
    | '/nets'
    | '/plans'
    | '/print'
    | '/standards'
    | '/studio'
    | '/supports'
    | '/teacher'
    | '/updates'
    | '/foldables/$id'
    | '/labs/$id'
    | '/plans/$id'
    | '/foldables/'
    | '/labs/'
    | '/plans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildRoute: typeof BuildRoute
  DrawRoute: typeof DrawRoute
  FoldRoute: typeof FoldRoute
  FoldablesRoute: typeof FoldablesRouteWithChildren
  LabsRoute: typeof LabsRouteWithChildren
  MathRoute: typeof MathRoute
  NetsRoute: typeof NetsRoute
  PlansRoute: typeof PlansRouteWithChildren
  PrintRoute: typeof PrintRoute
  StandardsRoute: typeof StandardsRoute
  StudioRoute: typeof StudioRoute
  SupportsRoute: typeof SupportsRoute
  TeacherRoute: typeof TeacherRoute
  UpdatesRoute: typeof UpdatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draw': {
      id: '/draw'
      path: '/draw'
      fullPath: '/draw'
      preLoaderRoute: typeof DrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fold': {
      id: '/fold'
      path: '/fold'
      fullPath: '/fold'
      preLoaderRoute: typeof FoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foldables': {
      id: '/foldables'
      path: '/foldables'
      fullPath: '/foldables'
      preLoaderRoute: typeof FoldablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/math': {
      id: '/math'
      path: '/math'
      fullPath: '/math'
      preLoaderRoute: typeof MathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nets': {
      id: '/nets'
      path: '/nets'
      fullPath: '/nets'
      preLoaderRoute: typeof NetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards': {
      id: '/standards'
      path: '/standards'
      fullPath: '/standards'
      preLoaderRoute: typeof StandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supports': {
      id: '/supports'
      path: '/supports'
      fullPath: '/supports'
      preLoaderRoute: typeof SupportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foldables/': {
      id: '/foldables/'
      path: '/'
      fullPath: '/foldables/'
      preLoaderRoute: typeof FoldablesIndexRouteImport
      parentRoute: typeof FoldablesRoute
    }
    '/foldables/$id': {
      id: '/foldables/$id'
      path: '/$id'
      fullPath: '/foldables/$id'
      preLoaderRoute: typeof FoldablesIdRouteImport
      parentRoute: typeof FoldablesRoute
    }
    '/labs/': {
      id: '/labs/'
      path: '/'
      fullPath: '/labs/'
      preLoaderRoute: typeof LabsIndexRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/$id': {
      id: '/labs/$id'
      path: '/$id'
      fullPath: '/labs/$id'
      preLoaderRoute: typeof LabsIdRouteImport
      parentRoute: typeof LabsRoute
    }
    '/plans/': {
      id: '/plans/'
      path: '/'
      fullPath: '/plans/'
      preLoaderRoute: typeof PlansIndexRouteImport
      parentRoute: typeof PlansRoute
    }
    '/plans/$id': {
      id: '/plans/$id'
      path: '/$id'
      fullPath: '/plans/$id'
      preLoaderRoute: typeof PlansIdRouteImport
      parentRoute: typeof PlansRoute
    }
  }
}

interface FoldablesRouteChildren {
  FoldablesIdRoute: typeof FoldablesIdRoute
  FoldablesIndexRoute: typeof FoldablesIndexRoute
}

const FoldablesRouteChildren: FoldablesRouteChildren = {
  FoldablesIdRoute: FoldablesIdRoute,
  FoldablesIndexRoute: FoldablesIndexRoute,
}

const FoldablesRouteWithChildren = FoldablesRoute._addFileChildren(
  FoldablesRouteChildren,
)

interface LabsRouteChildren {
  LabsIdRoute: typeof LabsIdRoute
  LabsIndexRoute: typeof LabsIndexRoute
}

const LabsRouteChildren: LabsRouteChildren = {
  LabsIdRoute: LabsIdRoute,
  LabsIndexRoute: LabsIndexRoute,
}

const LabsRouteWithChildren = LabsRoute._addFileChildren(LabsRouteChildren)

interface PlansRouteChildren {
  PlansIdRoute: typeof PlansIdRoute
  PlansIndexRoute: typeof PlansIndexRoute
}

const PlansRouteChildren: PlansRouteChildren = {
  PlansIdRoute: PlansIdRoute,
  PlansIndexRoute: PlansIndexRoute,
}

const PlansRouteWithChildren = PlansRoute._addFileChildren(PlansRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildRoute: BuildRoute,
  DrawRoute: DrawRoute,
  FoldRoute: FoldRoute,
  FoldablesRoute: FoldablesRouteWithChildren,
  LabsRoute: LabsRouteWithChildren,
  MathRoute: MathRoute,
  NetsRoute: NetsRoute,
  PlansRoute: PlansRouteWithChildren,
  PrintRoute: PrintRoute,
  StandardsRoute: StandardsRoute,
  StudioRoute: StudioRoute,
  SupportsRoute: SupportsRoute,
  TeacherRoute: TeacherRoute,
  UpdatesRoute: UpdatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
